### ISSUE TITLE
Improvement suggestions for "Files" tab

### ISSUE THREAD

**Issue by andersevenrud** [bithound/feedback#100]
It seems like some of the features from your previous UI has been retired, or possibly forgotten ? 

Before I was able to filter files by "Lint issues", "Duplicate functions" etc. and I can't seem to find these anywhere.

![Screenshot](http://i.imgur.com/2zrD0lM.png)

**Comment by carlosperez** [comment]
Hi @andersevenrud – we actually never had those features on that Files View (which was admittedly an oversight) – *but* we did add them in our last release so you should be able to filter much easier now. Enjoy!
