### ISSUE TITLE
Some comments on Dashboard

### ISSUE THREAD

**Issue by andersevenrud** [bithound/feedback#101]
Attached is a screenshot with notations on some comments I have about the Dashboard.

I can make a writeup if you cannot for some reason not view the [image](http://i.imgur.com/bfnPFda.png).

![Screenshot with notations](http://i.imgur.com/bfnPFda.png)

**Comment by carlosperez** [comment]
Hi @andersevenrud – thanks for the feedback. We have been making some incremental improvements to the dashboard in the past couple of months that address a few of the issues you mentioned. Hope it helps!
