### ISSUE TITLE
Suggestions for UI

### ISSUE THREAD

**Issue by andersevenrud** [bithound/feedback#102]
This is related to #101 .

I've been playing around with your current layout and made a mashup that kind of merges your old design and the new one. I realize that design is very subjective, but these are some of the things I came up with:

It's more or less the same, but has a bit more "air" and the repository menu has been merged with the blue bar. Also there are no more borders making it a bit easier on the eye (at least for me).

I'd really like to see a graph like you had previously for historic data.

**Edit: update in next comment below**

- ~~[link to raw image](http://i.imgur.com/xQVIqZY.png)~~
- ~~[link to code](http://codepen.io/anon/pen/vOqvMY)~~

**Comment by andersevenrud** [comment]
I did some changes... just added some more elements:

![Screenshot](http://i.imgur.com/i9JDHYR.png)

* [Source](http://codepen.io/anon/pen/vOqvMY)
* [Screenshot](http://i.imgur.com/i9JDHYR.png)

**Comment by andersevenrud** [comment]
@dansilivestru Any comments ? :)

**Comment by dansilivestru** [comment]
Hi @andersevenrud 

My apologies for the late reply here. The team and I have been reviewing your suggestions. Let me start by saying thank you for taking the time to provide us with such great feedback and creating these great mocks.

We have created internal issues for some of your suggestions already. I'll keep this issue open for us to provide you with updates.

I do want to reassure you that the graph will come back, although in a slightly different format. It the old design the graph was purely based on commits over time. However, with the introduction of dependency scoring, things had to change. As I'm sure you realize, a dependency you have might become outdated or insecure through no direct action of yours. Therefore graphing those of time needs to be done differently.

Thanks again for all of your hard work, it's very much appreciated. Stay tuned for updates :-)

**Comment by andersevenrud** [comment]
@dansilivestru No worries about response times.

> We have created internal issues for some of your suggestions already. 

Cool!

> I do want to reassure you that the graph will come back

Really nice to hear. Looking forward to that. Gotta love dem charts :)

> Thanks again for all of your hard work, it's very much appreciated.

This is pretty much what I do for a living, so just happy to be of help!

**Comment by carlosperez** [comment]
Hi @andersevenrud – we're going to close this issue and track it internally.
