### ISSUE TITLE
Wrong npm info

### ISSUE THREAD

**Issue by mathiasrw** [bithound/feedback#103]
The url https://www.bithound.io/github/agershun/alasql states

> npm install alasql
> last updated 3 months ago
> latest version 0.1.10

but opening npm gives

> 0.2.0 is the latest of 63 releases

Please make sure info on bithound is correct. 

ps: input: make the npm logo on the bithound site link to npm

**Comment by CSilivestru** [comment]
Hi @mathiasrw,

Thanks for reporting this! 
I'll update you as soon as I have any information on the issue.

**Comment by CSilivestru** [comment]
Looks like we had a minor caching issue with this particular repo. Should be all fixed up now -- thanks again for pointing it out :-).
