### ISSUE TITLE
How to remove projects from analysis?

### ISSUE THREAD

**Issue by jeffcharles** [bithound/feedback#104]
I have a few projects I'm no longer maintaining due to an employment change that I'd like to get off of my dashboard since I don't care about the scores any more. How do I do that?

**Comment by dansilivestru** [comment]
Hi @jeffcharles right now we populate your dashboard based on the project you have contributor rights to. We do plan on adding the ability to customize which projects you would like to see on the dashboard, however that feature there yet.

Are you still a contributor on these projects?
Are they Open Source or Private?

Feel free to email directly if you'd rather not put details out publicly: dan@bithound.io

**Comment by jeffcharles** [comment]
Okay, that's reasonable.

Yes I'm still a contributor and they are open source.

**Comment by dansilivestru** [comment]
Thanks. I'm going to leave this issue open and we'll use to update you as we make progress on allowing you to select the projects you want to see in your dashboard.

**Comment by fhemberger** [comment]
+1 on this.

Can you also please limit the initial project scan to own projects and ignore forks until explicitly selected?
I'd love a solution like Travis CI, where you can check/uncheck the repositories to be scanned. This would also unclutter the UI, if you have many projects.

**Comment by carlosperez** [comment]
Hi @jeffcharles and @fhemberger – we're going to track this issue internally to better stay on top of it. It's a feature that isn't on our immediate roadmap, but is definitely on our radar. Keep a an eye out on our newsletter, [changelog](https://www.bithound.io/changelog) and [blog](http://blog.bithound.io) for future feature updates.
