### ISSUE TITLE
Oops! Something went wrong!

### ISSUE THREAD

**Issue by JosefJezek** [bithound/feedback#105]
https://www.bithound.io/github/bower/bower

Please improve load page performance and stability of bithound.

**Comment by carlosperez** [comment]
Hi @JosefJezek – I apologize for issues you are experiencing. Performance and stability are things that we are constantly looking at here, and appreciate your patience. On top of that, we're looking at ways we can better improve messaging about errors so users can have a better understanding of what's going on with analysis.

**Comment by JosefJezek** [comment]
Thank you
