### ISSUE TITLE
Some questions regarding "bug prone" files

### ISSUE THREAD

**Issue by andersevenrud** [bithound/feedback#107]
So you probably figure out which file is bug prone by scanning the commit logs, but how do you tell the problem has been "resolved" ?

If I do a refactor or a rewrite of the code the problem is still part of the history, I get that, but the underlaying code that lead to the buggy behaviour might now be gone.

It seems that renaming such a file will remove the message, but does it dissapear on its own after a while ?

Just wondering since I'm in the process of splitting up one of my files into smaller parts, leaving the original file pretty much empty. The [warning] message would not make a lot of sence then.

Ref: #83, #54

**Comment by carlosperez** [comment]
Hi @andersevenrud – we take a look at many factors in determining this, but at its most basic it boils down to how often you commit and how many of those changes are bug fixes. In this situation, your original file, is still the bug prone file, so it might take time (and commits with no bug fixes) to make the issue disappear.
