### ISSUE TITLE
Automatically adjust settings for Node JavaScript

### ISSUE THREAD

**Issue by bahmutov** [bithound/feedback#11]
for example, Gruntfile.js should assume node environment and not complain about `module` and `require` keywords

**Comment by gtanner** [comment]
hey @bahmutov;

I ended up sneaking this in while I was adding JSX support. (undocumented of course): https://www.bithound.io/changelog

we will now just assume node and browser globals if they are not set when linting.
0.14.6
Apr 7, 2015
- We now support JSX files! We, of course, still support vanilla JavaScript and your hopes and dreams.
- Test files are special, so we now treat them as such! We've changed the way we analyze and score your test files!
- We'll start calling you out for including source files over 100KB in your projects.
- You look nice today!
```
