### ISSUE TITLE
Don't show repositories with only (yet) unsupported languages

### ISSUE THREAD

**Issue by fhemberger** [bithound/feedback#110]
The current list of repositories also shows projects consisting only of unsupported languages (e.g. Shell scripts, Dotfiles, Vagrant boxes, etc.). It would be great if those repositories would not be listed at all (or only shown grayed out).

GitHub API endpoint: https://developer.github.com/v3/repos/#list-languages
(yes, unfortunately, this is an extra API call per repository)

**Comment by carlosperez** [comment]
Hi @fhemberger – we used to attempt to determine the language of the repo before displaying it, but there were sometimes issues with what GitHub would report as languages. Sometimes their analysis wouldn't work, and we'd be hiding projects we shouldn't have been. As a result, we opted to show everything.
