### ISSUE TITLE
There's no JavaScript! 

### ISSUE THREAD

**Issue by VenomVendor** [bithound/feedback#111]
Oops! Can&#39;t quite do that! – bitHound

Trying to analyze [an repository](https://www.bithound.io/github/VenomVendor/Frontend-Development-Exercises) with no *.js in the root, show's 
* <b>There's no JavaScript! </b>
* GitHub recognizes repo as "JavaScript". 

<img width="849" alt="bitHound - bug - no javascript" src="https://cloud.githubusercontent.com/assets/1086927/9955171/9405a682-5e0c-11e5-9922-631b316a09d1.png">

**Comment by CSilivestru** [comment]
Hi @VenomVendor,

Sorry about the inconvenience. It looks like we're having some problems parsing out your filenames correctly in this case. I've identified the problem and we'll be issuing a fix for it soon. I'll keep you posted here.

Thanks for reporting this!

**Comment by CSilivestru** [comment]
We've deployed the fix and I manually kicked off a fresh analysis for your repo. It has been analyzed successfully and you're all good to go.

I will close this issue -- please re-open it if you have any more problems.

**Comment by VenomVendor** [comment]
Looks great.
That was fast.
