### ISSUE TITLE
eslint version detection issue again

### ISSUE THREAD

**Issue by sagiegurari** [bithound/feedback#112]
Since i can't open #93 for some reason, I'm creating a new issue.

It is again buggy and again stating that eslint version is not supported.
See https://www.bithound.io/github/sagiegurari/multiple-redis/blob/9400e37cb4a8df89bef589179a6b9e9424847176/lib/multiple-redis.js

in package json I have: "grunt-eslint": "latest"

**Comment by CSilivestru** [comment]
Hi @sagiegurari,

We put in some improvements to our eslint analysis yesterday to help solve this problem. I just ran your repository through again and it all looks good. Please let me know if anything still looks weird on your end.

**Comment by sagiegurari** [comment]
ok, I'll check

**Comment by sagiegurari** [comment]
how do I rerun in my other repos?

**Comment by CSilivestru** [comment]
Unfortunately we don't have a mechanism for that at the moment -- however, I'd be happy to re-run them for you. A new commit will also trigger an analysis.

If you'd like me to re-run them all, you could email me a list at chris@bithound.io. Is it all the repos under your username?

**Comment by sagiegurari** [comment]
yap. all repos under me.
There are only 5 of them.

**Comment by CSilivestru** [comment]
I'll get those going and I'll report back when they're complete.

**Comment by sagiegurari** [comment]
Thanks a lot

**Comment by CSilivestru** [comment]
Ok all repos have completed analysis and there are no eslint outdated errors anymore! I'm going to close this issue now but feel free to re-open it if you still notice something wrong that I missed.

**Comment by sagiegurari** [comment]
thanks for the help.
looks good.

**Comment by CSilivestru** [comment]
No problem -- thanks for the feedback
