### ISSUE TITLE
Support Visual Studio Online Git Repositories

### ISSUE THREAD

**Issue by Cecildt** [bithound/feedback#114]
It would be great if you can support Visual Studio Online Git repositories. This is where I host my private projects. It would be great to get them analyzed by bithound.

https://www.visualstudio.com/en-us/products/what-is-visual-studio-online-vs

**Comment by gtanner** [comment]
Thanks for letting us know about Visual Studio Online Git Repos.

We are currently focusing on GitHub and BitBucket support so I can't say when we would get around to adding more repository sources.
