### ISSUE TITLE
Link FILES is broken

### ISSUE THREAD

**Issue by sliday** [bithound/feedback#117]
I am at the panel: https://www.dropbox.com/s/4gql8uoxjaak976/Screenshot%202015-10-12%2011.51.19.png?dl=0

Here is what FILES is linked to: https://sliday/gnomie-backend//files

**Comment by carlosperez** [comment]
Hi @sliday – sorry for the issue you are seeing. I'll need to ask a couple of questions to help diagnose the problem: 

1. Were you able to see content on the project dashboard page (the screen you took that screenshot on)?
2. Are you still seeing this issue? I.e. does it happen all the time, or intermittently?

**Comment by carlosperez** [comment]
Hi @sliday - just checking in on this issue again. We haven't been able to reproduce it ourselves, but have seen other people mention it. If you can give us some more details, we'll take a look at it.

**Comment by carlosperez** [comment]
We are going to continue to monitor this bug. We haven't been able to reproduce ourselves, so any details would be appreciated. Please reach us at [support@bithound.io](mailto:support@bithound.io) as we are closing the feedback repository on GitHub to consolidate our support.
