### ISSUE TITLE
Github webhook

### ISSUE THREAD

**Issue by rstoenescu** [bithound/feedback#118]
Maybe I am mistaken, but I have the impression that Bithound only analyzes code if you visit its website. I would like an automatic analysis based on a Github webhook. I don't like to see Bithound fetching my repos each time I visit Bithound.

Please correct me if I got something wrong. Thanks!

**Comment by dansilivestru** [comment]
Hi @rstoenescu you are correct, we do not support webhooks... yet. We opted for very easy introductory use.

Webhook support is on our very near-term roadmap. Please stay tuned, we will be announcing it in our newsletter as soon as it's launched.

**Comment by rstoenescu** [comment]
Looking forward to the webhook.
Thanks and keep up the good work!

**Comment by ApfelUser** [comment]
+1

**Comment by carlosperez** [comment]
Hi @rstoenescu and @ApfelUser – just wanted to let you know we now let you set up webhooks on your projects! See our blog for more details: http://blog.bithound.io/automatic-commit-analysis-with-webhooks/

**Comment by rstoenescu** [comment]
Thanks!

**Comment by lenovouser** [comment]
:+1:
