### ISSUE TITLE
Problems with webhooks

### ISSUE THREAD

**Issue by andersevenrud** [bithound/feedback#119]
I recently moved my reposiotry over to an organizational account (and renamed it).

I'm having trouble setting up the webhooks at https://www.bithound.io/settings/github/os-js/OS.js/integrations.

If I try to click "Enable webhooks" i get: 

> Oh no! Something went wrong while trying to activate your webhook.
Did you grant bitHound third party access rights for this organization?

I go to the link provided and search for "bithound" under third-party access .. .but you do not show up.

I can manually add it, but cannot find the info to do so.

![Screenshot](http://i.imgur.com/NdJvdkc.png)

**Comment by carlosperez** [comment]
Hi Anders I just followed up via email on a resolution.
