### ISSUE TITLE
CI to search configs from `package.json` first, then from bithoundrc?

### ISSUE THREAD

**Issue by tunnckoCore** [bithound/feedback#120]
Also want to ask, cuz can't find answer for the moment .. any way to configure default lint engine?
I'm using standard, and it seems that bithound defaults to use jshint when not find any config/dotfiles (as jshintrc or eslintrc) in repository.

for example, https://www.bithound.io/github/tunnckoCore/parse-function

Sorry if issue is not for here :)

**Comment by carlosperez** [comment]
I've responded via email as we are no longer maintaining this project.

**Comment by tunnckoCore** [comment]
Oo yea, sorry, no problem :) I'll wait, my mail is on the commit log :)
