### ISSUE TITLE
JSX and ES6 support

### ISSUE THREAD

**Issue by rarous** [bithound/feedback#14]
It would be nice to have support for JSX (there are two posibilities 1. transform it before linting 2. use FB version of Esprima for analysis). 

It look like it also breaks on ECMA Script 6 syntax features.

**Comment by CSilivestru** [comment]
Hi @rarous,
We currently do not support JSX or other type safe variants of javascript (such as TypeScript). As of right now, it is not on our immediate roadmap. We want to focus enabling our users to write the very best javascript possible first.

As for ES6 syntax features, we use jshint as our linter so you can add the  `esnext` option to your `.jshintrc`. Please look here for reference: http://jshint.com/docs/options/#esnext

**Comment by rarous** [comment]
I have `esnext` enabled, but it still breaks on eg. Object Literal Property Value Shorthand. In result it says that I have unbalanced braces.

**Comment by CSilivestru** [comment]
`esnext` appears to offer partial support for ES6 syntax -- that could be the problem...
Would you be able to post the offending line and I'll dig a little deeper :-).
Thanks!

**Comment by CSilivestru** [comment]
Sorry I forgot to include my email address!
You can send it to me personally at chris@bithound.io.

**Comment by gtanner** [comment]
Hey @rarous, just a heads up we shipped JSX support.  Take it for a ride and let us know what you think.

**Comment by wolframkriesing** [comment]
Hey Gord, this sounds like a cool message ... do I have to turn on jsx? I get lint errors for jsx lines, like here https://www.bithound.io/github/tddbin/es6katas.org/blob/b708428fe8f25af43bc980c590e9898c8f977a71/src/server/index.js

**Comment by gtanner** [comment]
hey @wolframkriesing welcome back!

We are currently using the react-tools compiler which is failing on this file with:

```
Error: Parse Error: Line 1: Illegal import declaration
  index: 0,
  lineNumber: 1,
  column: 1,
  description: 'Illegal import declaration'
```

If I switch this out to the babel compiler it seems to work fine.  I will look into this a bit more and see if it is a matter of updating our react-tools dep, switching to babel or something else.

**Comment by wolframkriesing** [comment]
react now uses babeljs :)
https://twitter.com/sebmck/status/595366691082743808

--
Kind regards / Saludos / Mit freundlichen Grüßen
Things we think are important http://www.uxebu.com/universe/
Meet uxebus at http://www.uxebu.com/about-us/events/

Wolfram Kriesing, CTO
uxebu

kriesing@uxebu.com, mobile: +49 174 300 4595

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by gtanner** [comment]
9 hours ago! who says this javascript thing moves fast.

**Comment by wolframkriesing** [comment]
:) yeah just ran across after I wrote here too LOL

--
Kind regards / Saludos / Mit freundlichen Grüßen
Things we think are important http://www.uxebu.com/universe/
Meet uxebus at http://www.uxebu.com/about-us/events/

Wolfram Kriesing, CTO
uxebu

kriesing@uxebu.com, mobile: +49 174 300 4595

uxebu GmbH
Fraunhofer Straße 31e
86167 Augsburg

Amtsgericht Augsburg, Handelsregister HRB 28613
Directors: W. Kriesing, T. v. Klipstein

**Comment by gtanner** [comment]
hey @wolframkriesing, this slipped threw the cracks since the comments were on a closed issue, but deployed the new parser and reanalyzed your project.

Sorry about the wait.

**Comment by wolframkriesing** [comment]
If you need some more testimonials here we go https://www.bithound.io/github/wolframkriesing/es6-react-workshop/blob/e39b4a1ae246bafac5cfc79fc30e1e5988a17e5b/src/components/page.js#11-lint
