### ISSUE TITLE
Hapi.js module reporting vulnerability.

### ISSUE THREAD

**Issue by fourq** [bithound/feedback#15]
According to your results there's a vulnerability in the Hapi.js module. I talked with one of the hapi developers about this and was told that this was resolved back in version 6.1.0 (current 8.1.0). He asked me if you guys actually run all the tests or do you look a db based on the module, but I wasn't sure so here I am....asking =). Also he was able to point me to the commit where the patch took place: https://github.com/hapijs/hapi/blob/master/lib/response.js#L579. 

Here's a screen shot of the vulnerability alert: http://screencast.com/t/PHXPuvj6wPp

Can you shed some light one this?
Thanks

**Comment by gtanner** [comment]
Thanks for finding this.

Looks like a bug in our detection code where we are showing the alert all the time for a module that has had an advisory in the past.

I will get this fixed and push out a change shortly.

**Comment by fourq** [comment]
:+1:

**Comment by gtanner** [comment]
This will be in our next release (I will let you know as soon as it ships)

**Comment by gtanner** [comment]
This fix is now live.

Thanks for reporting it for us!

**Comment by fourq** [comment]
Thanks for letting us know!
