### ISSUE TITLE
Duplicate functions found in build artifacts

### ISSUE THREAD

**Issue by kpiascik** [bithound/feedback#17]
I'm getting a duplicate function in my analysis, but the duplicate is from a build folder.  I think this duplicate could/should be ignored.  This is for this file https://github.com/blackberry/Alice/blob/master/src/alice.plugins.caterpillar.js where duplicates are found here https://github.com/blackberry/Alice/blob/master/build/alice.js

**Comment by carlosperez** [comment]
Hi @kpiascik – thanks for reaching out with your feedback. This particular issue is a great candidate for introducing a `.bithoundrc` file to your project's root. You can specify what files/folders you would like bitHound to ignore. Build files would typically go in here.

For information on how to set it up see [this blog post](http://www.bithound.io/blog/post/ignoring-files-and-folders-in-bithound). Let me know if you have any questions getting this setup. 

Cheers,
Carlos
