### ISSUE TITLE
BitBucket support

### ISSUE THREAD

**Issue by kpiascik** [bithound/feedback#18]
It would be nice to support bitbucket.org as well as github.

**Comment by glasspear** [comment]
+1

**Comment by gtanner** [comment]
It is on our roadmap for sure!

**Comment by gtanner** [comment]
https://www.bithound.io/blog/post/bithound-announces-support-for-bitbucket

:) Enjoy

**Comment by glasspear** [comment]
Thanks @gtanner ! Already running it on some repos :) So far so good.
