### ISSUE TITLE
Firefox slows down on initial page loads

### ISSUE THREAD

**Issue by twolfson** [bithound/feedback#19]
I am using Firefox with Firebug enabled. I am noticing Firefox hanging when the page initially loads (e.g. when I visit the page, click on a repo). There doesn't seem to be a lot of content so I am not sure why that is. It usually hangs if it is rendering a lot of items or setting up a large UI (e.g. Google Docs).

**Comment by dansilivestru** [comment]
Hi @twolfson thanks for letting us know. Can you let us know what repository you're looking at? Feel free to email me directly dan@bithound.io if you'd rather not share it publicly.

**Comment by twolfson** [comment]
The pages thus far have been:

- Home page
    - https://app.bithound.io/
- Organization page
    - https://app.bithound.io/Ensighten
- Repo page
    - https://app.bithound.io/Ensighten/grunt-spritesmith

**Comment by gtanner** [comment]
I am thinking the main issue for this is we are using Polymer (https://www.polymer-project.org) for our pages, which is really cool and awesome.

BUT:

the only browser that isn't doing a non-native polyfill of the shadowdom is Chrome, so in FireFox and other browsers we end up with a rather large and slow version of our pages.

**Comment by gtanner** [comment]
Good news it can only get better as more browsers implement native support for Polymer and Web Components :)

**Comment by twolfson** [comment]
There should still be ways to make it work (e.g. spacing out rendering of new components rather than a batch which takes up the entire event loop). Have you done benchmarking on this to verify that is the bottleneck?

**Comment by carlosperez** [comment]
Hi @twolfson - our biggest bottleneck right now is the web components polyfill that Polymer uses. We're learning as we go with Polymer so any improvements we can make we will certainly look into. The good news is that Polymer is making big improvements to the polyfill early this year, so we hope to see Firefox and Safari's performance improve. [More info on Polymer's proposed updates this year](http://updates.html5rocks.com/2015/01/polymer-state-of-the-union).

**Comment by carlosperez** [comment]
Hi @twolfson - we did a bit of cleanup work on our front-end JS dependencies and have seen a bit of a performance improvement in Firefox. I hope this addresses some of your performance concerns, and we are still very much looking to implement the updated versions of Polymer (when they are released) which will hopefully provide even more performance gains.

**Comment by twolfson** [comment]
Yep, it feels more performant now. There are no major 5 second freezes, it is a bit progressive with content but it is better to see it loading then a lock-up.
