### ISSUE TITLE
Forks not listed

### ISSUE THREAD

**Issue by twolfson** [bithound/feedback#20]
Sometimes projects that are GitHub forks become separately registered projects entirely. It would be nice to see those listed.

**Comment by dansilivestru** [comment]
Love this suggestion! Marking this as a feature request and will internalize this. I'll keep this issue open so that we can update you on progress.

**Comment by carlosperez** [comment]
Hi @twolfson – we're moving feature requests to our internal issue tracker. Thank you for the suggestion!

**Comment by twolfson** [comment]
Aw, that's a shame. It would have been nice to see hear about the feature as it's developed and released. As a heads up, public roadmaps are becoming more prevalent -- here's an article by Trello on the subject:

http://blog.trello.com/going-public-roadmapping-with-a-public-trello-board/
