### ISSUE TITLE
on the dashboard, I only see 4 of my 10 organizations

### ISSUE THREAD

**Issue by pmuellr** [bithound/feedback#21]
Currently I see: phonegap, hshsbands, cordova, cloudfoundry-community.  The complete list should be visiible from my GitHub profile: https://github.com/pmuellr

I guess I'd like to see all of them, though that might be a bit busy.  Wouldn't mind being able to select which ones would show up in the dashboard.

**Comment by CSilivestru** [comment]
Hi @pmuellr,

Thanks for question!
It looks like all I can see on your GitHub profile are the 4 listed on bitHound. Could you please tell me if you signed up with public or private scope permissions (when you first authorized bitHound on GitHub)? Also, are the missing orgs completely private -- as in they have no public repos?

Thanks!

**Comment by seiyria** [comment]
I was also hit and surprised by this. See [here](http://webapps.stackexchange.com/questions/33932/new-github-organization-isnt-showing-on-my-profile) for a way to enable your org visibility (or just allow private repository access).

**Comment by dansilivestru** [comment]
I believe this has been resolved, closing. Please re-open if you're still seeing this behaviour.
