### ISSUE TITLE
don't include the org name in the project cards in the org view

### ISSUE THREAD

**Issue by pmuellr** [bithound/feedback#22]
here's what one of my org pages looks like:

![cloudfoundry-community_on_bithound](https://cloud.githubusercontent.com/assets/25117/5961149/8216ab62-a7a8-11e4-9f62-bc6c5abcd313.png)

here's a single "card" from that page

![cloudfoundry-community_on_bithound](https://cloud.githubusercontent.com/assets/25117/5961176/b98aff1c-a7a8-11e4-9498-ae80d1d37724.png)

The string "cloudfoundry-community/" is extraneous here, and obviously ends up eliding the actual project name.  I'd suggest, for cards on THIS page, that you just remove the org name, or do "left ellipsis" instead of right, so the ellipsis elides the org name from the left.

**Comment by carlosperez** [comment]
Hi @pmuellr - good idea! We're going to play around with those two options and see what works best. Thanks for the suggestion!

**Comment by carlosperez** [comment]
Hi @pmuellr - we just pushed up some modifications to the org view as you suggested. Thanks for the feedback and I hope this helps!

http://app.bithound.io/cloudfoundry-community

**Comment by seiyria** [comment]
Alternatively, in that view, show the org in `<small>` text on the line above the repository name. That way it's still there, but there's less of a risk of hitting boundaries like in the original example.

**Comment by gtanner** [comment]
We made note if that on our internal repo control issue @seiyria, we are going to close this in the meantime since the original issue has been fixed
