### ISSUE TITLE
ignore files and 3rd party deps

### ISSUE THREAD

**Issue by davidosomething** [bithound/feedback#23]
i keep a copy of backbone.js in my repo for instance
need to be able to specify that it shouldn't be graded

**Comment by CSilivestru** [comment]
Hi @davidosomething – thanks for reaching out with your feedback. This particular issue is a great candidate for introducing a .bithoundrc file to your project's root. You can specify what files/folders you would like bitHound to ignore.

For information on how to set it up please see this blog post. Let me know if you have any questions getting this going.

Thanks!

**Comment by seiyria** [comment]
Additionally, it seems that if you put your extra code in a "vendor" folder, it will be ignored. @CSilivestru you didn't actually link to a blog post there :P

It would be nice to have this noted somewhere on the app page, maybe... "Were we supposed to ignore this file? Learn how to set up your .bithoundrc file here [link]!"

**Comment by davidosomething** [comment]
here's the post: http://www.bithound.io/blog/post/ignoring-files-and-folders-in-bithound

**Comment by gtanner** [comment]
Closing this since `.bithoundrc` will work for these cases.

If there is any other issues please feel free to open another issue :)
