### ISSUE TITLE
"No javascript files found"

### ISSUE THREAD

**Issue by seiyria** [bithound/feedback#25]
I see this

![](http://puu.sh/feAgl/9493a0443b.png)

but in the [repository](https://github.com/seiyria/ntc.js) -- I see ntc.js right there. Bug?

**Comment by Connoropolous** [comment]
Hey Seiyria, 

we use language stats to detect whether we can analyze it or not, and that repo doesn't have language stats. That can be for a few reasons... 
it was forked using the github ui, or
the files were just added straight through the github ui

So if your situation is one of those then it's a known factor that we're still working to discover ways around. Let us know!

**Comment by carlosperez** [comment]
Hi @seiyria – by any chance is that a CoffeeScript generated JS file? GitHub doesn't treat those files as JavaScript which is why it may be showing that warning.

**Comment by seiyria** [comment]
It's possible I added that file through the github UI, as I can't seem to find language statistics. That's really strange, but makes sense.

@carlosperez It is not. I talked to the [creator](http://chir.ag/projects/ntc/) and put the library up on github so it could be `bower install`ed.

Thanks for getting back to me!

**Comment by CSilivestru** [comment]
Hi @seiyria,

Unfortunately this is an issue with language identification on GitHub's end but we will look into finding a way around this. Thanks for bringing it to our attention!

**Comment by Bishbulb** [comment]
I'm seeing this same problem as well in a repository that is hosting a mixture of Javascript and C# projects. 

Is bitHound only looking at the master branch? My master is empty, but develop has a few Angular apps in it.

**Comment by CSilivestru** [comment]
Hi @Bishbulb,

bitHound looks at the language stats given back from GitHub. When you go the that repo's homepage on GitHub, do you see a language bar at the top (directly above the branch drop down)? It should looks something like this:
![image](https://cloud.githubusercontent.com/assets/150235/6247872/b944dd94-b747-11e4-8c55-61fb66856180.png)

My guess is that GitHub is reporting languages on the wrong branch. Is master still set as your default branch for that repo?

Thanks!

**Comment by gtanner** [comment]
Hey,

We have since removed this limitation on the repo list pages, it should have cleaned up access to these repos.
