### ISSUE TITLE
CoffeeScript support?

### ISSUE THREAD

**Issue by seiyria** [bithound/feedback#26]
Sorry to be that guy, but most of my cool projects nowadays (ie, the ones I wanted to analyze) are written with CoffeeScript. A "simple" way to do this would be to copy the repo, compile each file to a CoffeeScript equivalent alongside itself, and analyze that, but CoffeeScript might not produce optimal JS, so it might bring along some strange issues.

**Comment by carlosperez** [comment]
Hi @seiyria – Right now we are concentrating on JavaScript and ES6, but we're investigating other languages including CoffeeScript.

**Comment by seiyria** [comment]
Great to hear! I'm looking forward to having another layer of analysis on top of my code.

**Comment by seiyria** [comment]
@gtanner does this mean support was added or decided against?

**Comment by gtanner** [comment]
;)

Sorry ... Just working on cleaning up some of these "roadmap" issues.  It is something that we are thinking about internally for sure but as @carlosperez mentioned we are focusing on ES6.

Keep an eye on our blog and changelog to track this better.
