### ISSUE TITLE
badge not updated in github

### ISSUE THREAD

**Issue by sagiegurari** [bithound/feedback#27]
check this issue https://github.com/github/markup/issues/224
seems you are not setting the no cache http header or expires so the badges are cached in github and not refreshed even after changes in bithound.

**Comment by carlosperez** [comment]
Thanks for pointing this out @sagiegurari - we will investigate and keep you posted on progress.

**Comment by carlosperez** [comment]
Hi @sagiegurari - We made some changes to the way we cache the badges. Can you let me know if you are still seeing these issues?

**Comment by sagiegurari** [comment]
that would not be easy to test. 
you could try to create some 'test' repo, with some issues there and than fix it and see if badge if updated.

**Comment by sagiegurari** [comment]
ok was able to verify that it now works good.
thanks for the fix.

**Comment by sagiegurari** [comment]
I still see sometimes old badges.
when I refresh i see other results (getting different things each time, guess i'm doing via different github servers or something).
anyhow, it looks like it is not working perfect.
can you verify you have disabled the cache?

**Comment by andersevenrud** [comment]
Bump. I had to add a hash to the image source to update it.

Could this be a Github related issue ? I see that the image source change to `camo.githubusercontent.com` when viewing files

**Comment by tonious** [comment]
Hi @sagiegurari, @andersevenrud  - `camo` is github's caching image proxy.  It pulls images from our server for display.  We've updated our web server configuration to play a little bit nicer with it.  

Unfortunately, there might be some older badges with a longer cache time still.  They'll update as they age out.

**Comment by andersevenrud** [comment]
@sagiegurari 10-4

**Comment by sagiegurari** [comment]
thanks. I believe disabling the cache on the response header is the best solution.
