### ISSUE TITLE
504 errors when opening files

### ISSUE THREAD

**Issue by sagiegurari** [bithound/feedback#28]
I'm trying to check the issues in files and 95% of the times i'm getting 504 errors.
very frustrating to work with a tool that says there are issues, but you can't see what they are.

**Comment by CSilivestru** [comment]
Hi @sagiegurari,

Thanks for checking out bitHound -- really sorry it's not working correctly for you!!
Could you please give me an example repo (or repos) so I can take a closer look for you? If you prefer, feel free to email me at chris@bithound.io.

Again, I'm really sorry for the frustration and I'll look into this problem asap.

**Comment by sagiegurari** [comment]
here is an example:

https://www.bithound.io/sagiegurari/event-emitter-enhancer/blob/390af075acf8d8e74a62cc85b630f535d0b85d3b/test/spec/event-emitter-enhancer-spec.js

it works sometimes, but most of the times, i just do refresh which waits for few minutes until i get the error.

**Comment by CSilivestru** [comment]
Thanks!

I'll look into the issue and update you soon.

**Comment by CSilivestru** [comment]
Could you please tell me what level of scope permission you granted to bitHound for GitHub?

**Comment by CSilivestru** [comment]
Hi @sagiegurari,

We have found the issue. We are currently working on a fix and investigating the root cause with GitHub.
Thanks for your patience and for reporting it to us!

**Comment by sagiegurari** [comment]
no problem

**Comment by CSilivestru** [comment]
Hi @sagiegurari,

This issue has been resolved and deployed. Could you please check again and let me know if you still experience problems?

Thanks!

**Comment by sagiegurari** [comment]
works good. thanks.
