### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by denis-sokolov** [bithound/feedback#3]
You really need badges! ![1](https://cloud.githubusercontent.com/assets/113721/4931624/43943a12-657c-11e4-81b4-44a6461cdce3.png)

Badges make sure I don't forget to check with bithound, it's right there, in my face. 
Badges promote your service to everybody else at an alarmingly quick rate.

Consider badges. Badges badges badges badges.

**Comment by carlosperez** [comment]
Hi @denis-sokolov and @bahmutov - you'll be happy to know that we've added badges for your repos! You can see more on our [badge blog post](http://www.bithound.io/blog/post/bithound-badge), or go to your repo on [bitHound](https://app.bithound.io) now and grab the snippets to add to your `readme` files.

**Comment by denis-sokolov** [comment]
Great job!
