### ISSUE TITLE
Lack of information for some files

### ISSUE THREAD

**Issue by sagiegurari** [bithound/feedback#32]
Some files are not graded as 100 but still there are no issues reported.
I think that should change and provide some explanation.

**Comment by CSilivestru** [comment]
Hi @sagiegurari,

Could you please give me an example of such a file?
We score a file on a number of different things, some of which are not currently reported to the user. 
We also score a file based on it's length but we only report it as a problem once it starts getting reasonably long.

If I had an example, I could take a closer look at the cause for you. As always, please feel free to email me at chris@bithound.io if you prefer :-).

Thanks!

**Comment by sagiegurari** [comment]
here is an example:

https://www.bithound.io/sagiegurari/node-go-require/blob/d6c339b321a7b9b3487c19ea07a1ee038efb2cf4/Gruntfile.js

also from what i read, you use the rules defined in the jshintrc file, but max lines is not a validation checked by jshint at all.

**Comment by CSilivestru** [comment]
That's correct. We wrote a custom tool to determine the file length.
I will look into the Gruntfile for you and get back to you.

**Comment by sagiegurari** [comment]
no need for the grunt file, it was just an example to understand why there are issues but they are not actually listed in the UI

**Comment by dansilivestru** [comment]
With the addition of some of the new insight badges as well as more information in the "learn more" section, I believe this can be closed. Please feel free to re-open.

**Comment by sagiegurari** [comment]
Ya, i think it is ok now.
