### ISSUE TITLE
Better responsive UI for screen in vertical orientation

### ISSUE THREAD

**Issue by erhhung** [bithound/feedback#33]
The web UI is too wide if my browser window is shown on a screen in vertical orientation. My screen is 1200x1920, which is plenty big, but the links on the right panes are all clipped, and on a view such as "dependencies/npm", the module column is so wide that the most important column, status, is mostly clipped.

**Comment by carlosperez** [comment]
Hi @erhhung –  we recognize that as a current limitation of our UI and do plan on making it responsive at a later date.

**Comment by gtanner** [comment]
We will track this better internally with our ongoing API / design tweaks.
