### ISSUE TITLE
UMD wrapper causing duplicate code issue

### ISSUE THREAD

**Issue by interactivellama** [bithound/feedback#34]
In our library, [Fuel UX](https://github.com/ExactTarget/fuelux), all our jQuery plugin controls are wrapped in a [UMD wrapper](https://github.com/umdjs/umd/blob/master/jqueryPlugin.js). 

Any suggestions for making this "error" disappear?

**Comment by dansilivestru** [comment]
Hi @interactivellama, thanks for the feedback. Replied to you via email on this. I'll keep this issue open until we're both satisfied that we have a good answer.

**Comment by gtanner** [comment]
Hey @interactivellama. 

I opened a pull request (https://github.com/ExactTarget/fuelux/pull/1169) to help address your duplicate code issues.

**Comment by gtanner** [comment]
I am going to close this since a lot more is happening on the PR on that project.

**Comment by interactivellama** [comment]
Absolutely.
