### ISSUE TITLE
After login, home page doesn't load

### ISSUE THREAD

**Issue by vernak2539** [bithound/feedback#36]
having an problem getting the home page to load after login. Keep getting redirected to the "Opps" page. Screenshot below.

![bithound](https://cloud.githubusercontent.com/assets/521270/6615973/0ac64396-c8a1-11e4-8851-e4a2739be0ba.PNG)

**Comment by CSilivestru** [comment]
Hi @vernak2539,

Thanks for reporting this! 
Your fork of https://github.com/Kevin-Wei/code-problems is resulting in an error case that we were not handling properly. I'm working on a fix and will let you know when it's resolved.

Sorry for the inconvenience!

**Comment by vernak2539** [comment]
Sounds good. Thanks!

**Comment by CSilivestru** [comment]
The fix has been applied and deployed! That problem repo will just not appear in your list now.

Could you please try again and let me know if you're still experiencing problems?

**Comment by vernak2539** [comment]
That seems to have done it. Thanks!
