### ISSUE TITLE
public api

### ISSUE THREAD

**Issue by piranna** [bithound/feedback#37]
I've been looking on the site for a public api and didn't find any docs, there is any way to access to BitHound data? A rest api or better a npm package?

**Comment by dansilivestru** [comment]
Hi @piranna Thanks so much for your comments. We don't have a public API... yet. It's on our roadmap and work will be starting on it shortly. In the mean time, we would love to hear from you on what kind of data you would like to see exposed.

We'll keep this issue open so that we can easily update you on our progress.

**Comment by piranna** [comment]
I'm mostly interested on the code quality statistics, combining BitHound with CoverAlls could easily allow to know the maturity of a project, and develop tools to fetch this data recursively over a project dependencies to know the general state of a project and where should it be improved (a 100% of test coverage on a project with a lot of untested and unstable dependencies is mostly useless...).

**Comment by lambrojos** [comment]
tJust being able to retrieve basic aggregate statistics on a branch would be awesome. 
I'm thinking about a continuous integration environment where such metrics could determine if a branch could be built/deployed.. if somebody could write a plugin for integrating bithound with jenkins or strider or similar I would be super happy

**Comment by piranna** [comment]
I have the same use case, integrate BitHound on CI :-)

**Comment by carlosperez** [comment]
Hi @piranna and @lambrojos – we're moving this issue internally to track it there. For an update, obviously we haven't released a public API. It's not on our immediate roadmap, but we'll keep it on our radar. I recommend you keep a an eye out on our newsletter, [changelog](https://www.bithound.io/changelog) and blog for our feature updates.
