### ISSUE TITLE
how to specify a branch?

### ISSUE THREAD

**Issue by anand9** [bithound/feedback#38]
Now it takes master branch as default, i wanted to check another branch. But that option was not found. So how to specify a branch?

**Comment by dansilivestru** [comment]
Hi @anand9 thanks so much for reaching out. Multiple branch analysis is on our roadmap and coming really soon. We'll keep this issue open and update you as soon as that feature launches.

Happy coding!

**Comment by gtanner** [comment]
Just a heads up that we launched multiple branch analysis.  Please take a look and let us know what you think.
