### ISSUE TITLE
Lint warnings should space out code

### ISSUE THREAD

**Issue by JaKXz** [bithound/feedback#4]
When there are lots of warnings in a file, they overlap each other and make it hard to read. I think you need to have each warning space out the file, or have the warnings come in inline with the code. 

![screenshot 2014-11-06 13 16 31](https://cloud.githubusercontent.com/assets/2642545/4941274/60b46134-65e1-11e4-84f0-b1be1888d35b.png)

**Comment by carlosperez** [comment]
Hi @JaKXz and @BrianJacklin - you've probably already seen it, but our revamped file view has addressed this issue! https://www.bithound.io/blog/post/introducing-our-revamped-file-view
