### ISSUE TITLE
Chance of getting old dependency data when processing

### ISSUE THREAD

**Issue by gtanner** [bithound/feedback#40]
Found by @appersonlabs
(https://twitter.com/mattapperson/status/577885360568590336)

Looking into this there is a chance that if the processing of the dependencies hits the same cpu instance of a previous commit, we could get a cached package.json.

This is due to us using node's require to load in the package.json:

```
var package = require('package.json');
```

To prevent this we should just use `fs.readFile` to be safe

**Comment by DamonOehlman** [comment]
Yep, I've just seen this with some stuff I've seen on [`rtc-quickconnect`](https://www.bithound.io/github/rtc-io/rtc-quickconnect/dependencies/npm).  I'm guessing another of the rtc.io packages used an older version of a package (red flag was raised over `rtc-tools`) which was definitely ok in recent versions of the package.json file.

**Comment by gtanner** [comment]
We had hotfixed this issue, but forgot to close this issue:

From our changelog (https://www.bithound.io/changelog)
```
0.14.1
Mar 19, 2015
You can depend on our dependencies after we squashed a bug that was preventing us from not checking your current versions.
Sometimes we trip over complexity ourselves; we fixed a bug that would sometimes not show the full function that has a complexity issue on it.
```
