### ISSUE TITLE
Badge for a "yet to be analysed" repository

### ISSUE THREAD

**Issue by DamonOehlman** [bithound/feedback#41]
Wondering if it's possible to have a badge for a repo that is yet to be analysed return a placeholder image rather than the default 404 that is happening at the moment.  This may seem like a strange request, but I just added bithound badge generation to a tool I use for helping maintain my READMEs (see: https://github.com/DamonOehlman/gendocs) which is now adding a bithound badge by default.

This results in broken images on repos until I activate the report, which admittedly I do pretty much straight away but it would be nice to have a "bithound | TBD" badge or something.

**Comment by dansilivestru** [comment]
Thanks for the feedback @DamonOehlman. That's a very good point, we've always assumed you'd analyze a project first and then add a badge :-)

We've opened an internal issue for this, but I'm going to keep this issue open so we can update you with our progress.

**Comment by DamonOehlman** [comment]
Cool Dan - thanks :)

**Comment by mathiasrw** [comment]
Any news on this?

**Comment by dansilivestru** [comment]
Not yet :( However, we have now officially assigned it internally and I'll make sure it moves up on our priority list. Thanks for the nudge :-)

**Comment by mathiasrw** [comment]
:+1:

**Comment by DamonOehlman** [comment]
Awesome!

**Comment by carlosperez** [comment]
Hi @DamonOehlman and @mathiasrw – in our last release we changed our 404 response on unknown badges to `analyze now` badges. Check it out :)

![analyze now on bitHound](https://www.bithound.io/github/superawesome/superproject/badges/score.svg)

**Comment by mathiasrw** [comment]
Great !
