### ISSUE TITLE
getting "Oh no!" on my bitbucket private repo after several commits pushed

### ISSUE THREAD

**Issue by dan-luk** [bithound/feedback#43]
not sure what other info I can provide

**Comment by CSilivestru** [comment]
Hi dan-luk, 

Since this is a private repo, would you be willing to send me a screenshot of your error page at chris@bithound.io?

**Comment by dan-luk** [comment]
Chris: done

**Comment by dan-luk** [comment]
it may relate to the fact that the project shows 0 dependencies which is not a case

**Comment by CSilivestru** [comment]
This has been resolved offline :-).
