### ISSUE TITLE
Trouble analyzing bitbucket repo/Never finishes

### ISSUE THREAD

**Issue by surajreddy** [bithound/feedback#44]
Hi there,

Myself and another member of my team are having trouble getting a bitbucket repo analyzed - it just never finishes. A github clone of this project is analyzed successfully.

Here's the screenshot - the repo stays stuck on this screen:
![screenshot_031815_015832_pm](https://cloud.githubusercontent.com/assets/80290/6715740/de4c6770-cd76-11e4-888d-82c04c90c028.jpg)

Let me know if I can provide anything else to help with this.

- Suraj

**Comment by tonious** [comment]
Hi Suraj,

I've manually re-analyzed this project, and it looks like it's succeeded.  Could you check on your end?

Thanks,

  -- Tony.

**Comment by surajreddy** [comment]
Hi Tony,

We still have the same problem - it still shows up in the "Choose to Analyze" list, and if I click it it starts processing again:

![screenshot_031815_034609_pm](https://cloud.githubusercontent.com/assets/80290/6717874/e7f4251a-cd85-11e4-930c-11925e361731.jpg)

**Comment by tonious** [comment]
Hi Suraj,

Looks like we had an index leftover from our pre-BitBucket days.  This prevented us from analyzing the BitBucket version of mozzaz/handheld as we already had the GitHub version in our database.  We've fixed it to respect both providers, and you should be good to go now.

Thanks, 

  -- T.

**Comment by surajreddy** [comment]
Awesome, thanks! :)
