### ISSUE TITLE
Bitbucket Open Issues Inaccurate - Resolved/Closed issues show up as open

### ISSUE THREAD

**Issue by surajreddy** [bithound/feedback#45]
Resolved/Closed issues show up as open:
![screenshot_031815_051221_pm](https://cloud.githubusercontent.com/assets/80290/6719617/31c322c0-cd92-11e4-9bb5-f79e586bfdbb.jpg)

Actual Status:
![screenshot_031815_051533_pm](https://cloud.githubusercontent.com/assets/80290/6719642/63f4232a-cd92-11e4-80d4-f2af4299442a.jpg)

**Comment by surajreddy** [comment]
This isn't a big deal for us, but just reporting it in case it's not a known issue yet.

**Comment by gtanner** [comment]
nice catch!

**Comment by Connoropolous** [comment]
Hi @surajreddy 

We've now resolved this issue, thanks again for catching it!
