### ISSUE TITLE
Bitbucket Repo not being analyzed

### ISSUE THREAD

**Issue by surajreddy** [bithound/feedback#46]
Hi there,

Our repo hasn't been analyzed right since the first time. It's been like this for a few days now:
![screenshot_032415_010558_pm](https://cloud.githubusercontent.com/assets/80290/6807719/8573b22a-d226-11e4-92ff-5f528de0120c.jpg)

We've had a previous issue with the same repo as well, #44 

https://www.bithound.io/bitbucket/mozzaz/handheld

Anything we can do on our end to fix this?

Thanks!

**Comment by dansilivestru** [comment]
Hi @surajreddy Thanks for letting us know. We're on it. I'll keep you posted on our progress.

**Comment by CSilivestru** [comment]
Hi @surajreddy,

It looks like a batch job was using invalid auth tokens for that repo. I think I got somewhere with it and it should be in a clean state now -- could you please revisit the page and let me know if it errors again for you?

Thanks!!

**Comment by surajreddy** [comment]
It's working great now, thanks @dansilivestru & @CSilivestru! :+1:
