### ISSUE TITLE
Make repo owner aware of bithound

### ISSUE THREAD

**Issue by dan-luk** [bithound/feedback#47]
Here is cool feature which will benefit BitHound dramatically as well as repo owners.

Scenario:
As a user I select to bit-bite the repository which does not belong to me and which is not yet analyzed.
Once analysis is completed, I can be presented with the button saying "Let owner know!"
On pressing this button, system will send notification to repo owner saying "Dan Lukinykh asked bithound to analyze your github repository "easy-config" and here is result: 66.  Maybe you want to improve your code?"

**Comment by dansilivestru** [comment]
Hi @dan-luk I really like the idea for this kind of feature. We've already implemented a "share" button at the top right, but to notify the owner, you would need to know their email address. We definitely want to avoid any ability of spamming the owner of a project.

In the case where an open source project scores poorly, we have to remember that someone put hard work and time into creating a project that the rest of us get to use for free. Criticizing the project might not result in as positive an outcome from the author/owner as we would all like.

We do have a feature that allows you to open an issue on a project (assuming they have issues enabled) on specific areas of the project that require attention. This notification will definitely go to all of the contributors for that project (i.e. the owners).

Another thing to consider is that the open source (OSS) community thrives on, well... community contributions. It is our hope that bitHound will provide everyone insight on how a project can be improved. It is also our hope that individuals, like yourself, which love a particular OSS project but are concerned with it's bitHound score would contribute to that project to make it better.

What better and more philanthropic way to let someone know about a poor bitHound score than to issue a pull request into that project to improve that score. You can then use bitHound to justify the changes you've made :wink: 

ps. here's an active conversation where we've offered our help to improve a project we use extensively and love: https://github.com/caolan/async/issues/720#issuecomment-87809271

**Comment by dan-luk** [comment]
Hi Dan,

That makes total sense.  Thanks for your time and great follow up!

Dan

**Comment by dansilivestru** [comment]
Cleaning this up and closing.
