### ISSUE TITLE
JavaScript inside HTML files?

### ISSUE THREAD

**Issue by RapsIn4** [bithound/feedback#48]
Bithound doesn't seem to detect JS inside HTML files.

**Comment by dansilivestru** [comment]
Hi @RapsIn4 that is correct, we don't detect JS inside HTML files, but it is on our roadmap. However, even when we do, I believe the recommendation will be to have you extract your JS into a separate file and include it with a ```<script>``` tag. We will likely allow for small inline code blocks.

May I ask why you're keeping your JS code in your HTML file?
