### ISSUE TITLE
oh no! Something went wrong

### ISSUE THREAD

**Issue by bkominek** [bithound/feedback#49]
We're getting the "Oh no! Something went wrong while analyzing this repository" error message on our bitBucket repo, so there hasn't been any commits analyzed since March 25.
![screen shot 2015-03-31 at 2 36 45 pm](https://cloud.githubusercontent.com/assets/1672797/6926422/1d036d50-d7b4-11e4-9e03-dd749ab29795.png)

**Comment by dansilivestru** [comment]
Hi @bkominek thanks. We've actually identified the root cause for this and have a Hotfix ready to go out shortly.

We'll keep this issue open and use it to inform you as soon as the fix is in.

Again, sorry for the inconvenience.

**Comment by bkominek** [comment]
that's fantastic!  Thanks

**Comment by dansilivestru** [comment]
Hi @bkominek the issue should be fixed now and should hopefully not return. Can you please check on your end and make sure everything is good?

**Comment by bkominek** [comment]
everything seems to be working fine now.  Thank you
