### ISSUE TITLE
A techdebt summary dashboard

### ISSUE THREAD

**Issue by DamonOehlman** [bithound/feedback#50]
Love the new techdebt feature :) With the amount of repos I have though it would be great if it's possible to get a report on where the techdebt is.

**Comment by dansilivestru** [comment]
Hi @DamonOehlman my apologies for the late reply here. I really like this idea, thank you for suggesting it.

Would you expect to have a "global" techdebt view? Or would you like a weekly summary notification email with the amount of techdebt in each of the repositories you care about? Or... do you have a different suggestion?

We'll keep this issue open to track progress on this.

**Comment by DamonOehlman** [comment]
@dansilivestru No probs.  My initial thoughts were for a "global" techdebt view, but the weekly email would probably work too.  I envision bithound being my code quality dashboard in the future which shows me all the stuff I need to make better, so being able to get an overall view of my techdebt across repos would be great (with the intention of hitting Techdebt 0).

**Comment by carlosperez** [comment]
Hi @DamonOehlman – thank you for the feedback. We're moving feature requests internally to track them there. Keep a an eye out on our newsletter, [changelog](https://www.bithound.io/changelog) and [blog](http://blog.bithound.io) for our feature updates.
