### ISSUE TITLE
[Minor] Spelling Mistake

### ISSUE THREAD

**Issue by PeterKruzlics** [bithound/feedback#52]
Hello,

There are a few times when I've used the app and noticed that "indicates" is misspelled as "inidicates".
Not a huge problem, more of a minor inconvenience :)

Thanks,
Peter

**Comment by dansilivestru** [comment]
Hi @PeterKruzlics thanks so much for reporting this! We'll have it fixed ASAP.

**Comment by gtanner** [comment]
It was fixed so fast that we forgot to close this issue :)

Thanks for reporting @PeterKruzlics.
