### ISSUE TITLE
churn and bug prone for small projects

### ISSUE THREAD

**Issue by sagiegurari** [bithound/feedback#54]
while there are many big js projects out there like angularjs, sails and so on... there are many many more small projects that are made up for 1-3 js files like jquery plugins, express middlewares and so on...
the churn and bug prone comments from bithound are set if a certain file changes a lot but its like saying to those small projects: "don't do any development"
ALSO, saying bug prone without checking coverage of automatic test cases is pretty useless.

for example one of my projects:
https://www.bithound.io/github/sagiegurari/event-emitter-enhancer/master/files
i got 100% test coverage and the project is basically 2 js files.
it is strange comments to get for such a project with many mocha tests and 100% coverage.

I say, if you can't tell, don't guess.
it is more harm than help.

**Comment by dansilivestru** [comment]
Hi @sagiegurari Thank you so much for your feedback. You make some really great and valid points when it comes to smaller projects.

As for bug prone files. I think it's important to keep in mind that you might have 100% test coverage while still having bugs in your code. We look at the ratio of your bug-fix commits to your non-bug-fix to draw our conclusions. 

That being said, we are looking into all of these things. I'll keep this issue open and will continue to post updates here.

Thanks again!

**Comment by sagiegurari** [comment]
what is a bug-fix commit and a non-bug-fix commit? how can you tell that?

**Comment by dansilivestru** [comment]
![magic](https://cloud.githubusercontent.com/assets/366327/7302313/78171796-e9b6-11e4-8ab2-c83cc859325f.jpg)

On a serious note :) We do some natural language processing on our end to distinguish between bug-fix and non-bug-fix commits. We're still perfecting our algorithms.

Looking at the history of the file in question: https://github.com/sagiegurari/event-emitter-enhancer/commits/da42e65d63a71839528601dbea8f429d95884500/lib/enhanced-event-emitter.js it does look like 3 out of the 12 commits on that file were addressing an issue, so... a historic bug density of 25%. Right now, we start checking for bug density on a file only once it has had more than 10 commits, that might be a bit too early.

We'll continue to perfect this and I'll keep this issue open for now. Would love to hear your thoughts on this as well.

**Comment by sagiegurari** [comment]
need to understand that algo, since none of the commits were actually bug fixes.
they were either new features, doc changes, lots of refactoring and last commit was to prevent possible issue if api is misused.

I think that maybe if a commit is connected to some github issue AND that github issue is labeled bug, than it can be defined as a bug fix commit. I'm pretty sure bitbucket to similar concept.
Also really need some way to connect that to unit testing that run as part of the CI builds, so if you can connect via some coverage reporter (like converall does) than you will have more insight if a changed area is tested or not. but i guess that might be a too major change in bithound.

**Comment by sagiegurari** [comment]
also, when multiple people work on a project, you have lots of merge commits.
those might also seem to change files, but are not really fixes, just merges.
need to be careful not to count those. not sure how to detect them however.

**Comment by carlosperez** [comment]
Hi @sagiegurari – thank you for the feedback, we'll be moving this issue internally. Keep a an eye out on our newsletter, [changelog](https://www.bithound.io/changelog) and [blog](http://blog.bithound.io) for our feature updates.

**Comment by sagiegurari** [comment]
I'm not sure what is the resolution. I don't see anything in the links regarding it.
And if it is future, than I suggest to keep issue open until you publish in your blog something about it.
Otherwise, how am I supposed to know what is being done regarding this specific item.

**Comment by carlosperez** [comment]
Hi @sagiegurari – I understand your frustration, and I apologize for the delay in getting back to you in the first place, as well our handling of this to close the issue.

We have found that it has proven difficult to stay on top of bithound/feedback issues given that we are now trying to take a more broad approach with our blog and newsletter. As such, we are planning on closing the bithound/feedback repository to help keep focus on updating our customers through the other channels just mentioned. Our in-app feedback system (Intercom) allows us to stay on top of issues better and suggest that as a feedback mechanism going forward.
