### ISSUE TITLE
bad link - "VIEW ALL ANALYZED FILES" button

### ISSUE THREAD

**Issue by sagiegurari** [bithound/feedback#55]
check https://www.bithound.io/github/sagiegurari/event-emitter-enhancer, than click the "VIEW ALL ANALYZED FILES" link.
it shows oops its not a branch error, and i have to fix the url to add 'master' to it before /files.
https://www.bithound.io/github/sagiegurari/event-emitter-enhancer/files -> bad link
https://www.bithound.io/github/sagiegurari/event-emitter-enhancer/master/files -> fixed link

**Comment by gtanner** [comment]
Thanks for reporting this!

Has since been fixed.
