### ISSUE TITLE
.bithoundrc test key ignores ignore key

### ISSUE THREAD

**Issue by mwbrooks** [bithound/feedback#56]
That title is so meta.

From my experience, I can't ignore a path inside a test folder. There is a good chance that I'm doing something wrong.

In [phonegap/phonegap-app-hello-world](https://www.bithound.io/github/phonegap/phonegap-app-hello-world), I've added `www/spec/lib/**` to my ignore list while having `**/spec/**` added to my test list. Unfortunately, the spec's library files are still being analyzed.

Here is the `.bithoundrc` for the project:

https://github.com/phonegap/phonegap-app-hello-world/blob/master/.bithoundrc#L3

**Comment by dansilivestru** [comment]
I think you might have a malformed .bithoundrc file. Looks like a dot rather than a comma on this line: 

https://github.com/phonegap/phonegap-app-hello-world/blob/master/.bithoundrc#L51

Let me know if that fixes it.

**Comment by dansilivestru** [comment]
love the issue title :-)

**Comment by mwbrooks** [comment]
That did it! Thanks!

As a heads up, the `.bithoundrc` was a copy & paste from the [Ignoring files and folders](https://www.bithound.io/blog/post/ignoring-files-and-folders-in-bithound) blog post. There was also a missing closing array bracket. It would probably be good to add a revision to the gist and update the blog post link.

Cheers!

**Comment by dansilivestru** [comment]
Well... that's embarrassing! I've fixed the gist, thanks for letting us know.

**Comment by gtanner** [comment]
Thanks for catching this: looks like @dansilivestru cleaned up the gist: https://gist.github.com/dansilivestru/b3f127f9736ab7cb36bb/revisions

**Comment by mwbrooks** [comment]
Nice!
