### ISSUE TITLE
This is so not a branch shows up when attempting to access some Bitbucket repos.

### ISSUE THREAD

**Issue by CSilivestru** [bithound/feedback#57]
If a repo does not have a main branch set, it may result in bitHound not recognizing an url without a branch specified.

A workaround for the user would be to set a main branch on the repo.
We will keep this open as we work towards a fix.

**Comment by gtanner** [comment]
Also logged a bug on bitbucket: https://bitbucket.org/site/master/issue/11260/default-branch-is-not-populated

**Comment by gtanner** [comment]
Seems to be a little bigger of a problem when there is no master branch.
