### ISSUE TITLE
404 Error when switching to branches from main repository view

### ISSUE THREAD

**Issue by JUhrig** [bithound/feedback#58]
I may have missed a feedback which already states this issue, or I am doing something wrong on my end either way ill leave this here. The steps I took to produce the issue are, click on a repository view --> once it loads select a branch from the top right branch drop down menu click an UNANALYZED branch and get redirected to a 404 page.

**Comment by CSilivestru** [comment]
Hi @JUhrig,

Would you be willing to let me know which repo and branch you had this behaviour on? If you'd like to continue this conversation offline, you can reach me personally at chris@bithound.io.

Thanks!

**Comment by CSilivestru** [comment]
Leading issue is this: https://github.com/bithound/feedback/issues/59

Closing this issue and tracking in the other :-).
