### ISSUE TITLE
Branch names with a '/' in them result in 404 

### ISSUE THREAD

**Issue by CSilivestru** [bithound/feedback#59]
Any branch names with a forward slash matches to an invalid route in bitHound.

**Comment by davidwood** [comment]
We use the Gitflow branching model, so this issues prevents us from using bitHound on any of our feature branches, which is primarily when we want to use it. We can always access the pages by manually encoding the / in the branch name, but its a hassle.

**Comment by dansilivestru** [comment]
This has now been deployed as per: https://www.bithound.io/changelog

@davidwood please let us know if you're still seeing this issue.

**Comment by davidwood** [comment]
This issue is fixed for me

**Comment by dansilivestru** [comment]
Great to hear, thanks for checking :-)
