### ISSUE TITLE
Allow files to be ignored

### ISSUE THREAD

**Issue by kpdecker** [bithound/feedback#6]
https://app.bithound.io/wycats/handlebars.js

We have a number of errors reported in test files, which we don't care about THAT much or 3rd party libs that we don't care about at all. It would be awesome if these files could be ignored, preferably through the UI of the app, vs. comments/config files/etc

**Comment by gtanner** [comment]
Closing this since we have since added the `.bithoundrc` feature.

if you have any more questions @kpdecker, just let us know :)
