### ISSUE TITLE
Any thoughts to supporting ESLint instead of JSHint

### ISSUE THREAD

**Issue by mtscout6** [bithound/feedback#61]
With the latest changes with React and ES6 JSHint has not been cutting it for us. We've been using ESLint as it is able to check against both language and framework (Mocha, React, etc.) related concerns.  I'm asking in regards to https://www.bithound.io/github/react-bootstrap/react-bootstrap

**Comment by dcrockwell** [comment]
+10

lack of `eslint` and `eslint-babel` support is the only issue preventing us from being able to generate useful bithound scores.

It is our team's belief that `eslint` and `eslint-babel` (officially endorsed by the author of `eslint`) are the new de facto standards for linting javascript source files.

**Comment by CSilivestru** [comment]
Hi @mtscout6 and @dcrockwell,

I'm happy to let you know that, with our recent implementation of eslint, we now support `eslint` and `eslint-babel`! I'll close this issue but please reopen it if you have any problems :-).

**Comment by mtscout6** [comment]
Thanks guys!
