### ISSUE TITLE
some npm modules are showing as unused when they are used via scripts

### ISSUE THREAD

**Issue by dansilivestru** [bithound/feedback#62]
As per this example here: https://www.bithound.io/github/Microsoft/TypeScript/master/dependencies/npm

We are aware of this issue and are tracking internally. Opening this issue for public visibility.

**Comment by gtanner** [comment]
There are some modules you include as dependencies that you will never require (test runners, linters, build systems).  Currently we are marking those as unused.

**Comment by dansilivestru** [comment]
I wonder if we shouldn't just exclude this check completely for dev-dependencies? This would be a very quick change since ```depcheck``` support exclusion of dev-dependencies.

**Comment by nelsonic** [comment]
:+1: would be good to see this fixed. let us know if you need another pair of eyes on it.
![bithound-devdeps-not-used](https://cloud.githubusercontent.com/assets/194400/7788093/0f6040ba-0225-11e5-973d-41a16d8d5b3e.png)

**Comment by andersevenrud** [comment]
+1

I'd really like too see a option for this in *bithoundrc*, maybe something like:

```
{
  "ignore_dependency": [
    "grunt"
  ]
}
```

**Comment by carlosperez** [comment]
Thank you for the suggestion, @andersevenrud – we're taking a look at how we can address this issue and we'll be taking that into consideration.

**Comment by gtanner** [comment]
We landed a fix for this here: https://www.bithound.io/github/sagiegurari/angular-web-notification

**Comment by nelsonic** [comment]
@gtanner does it also ignore `devDependencies` ...?
