### ISSUE TITLE
[TypeScript] HACK/TODO Techdebt Not Showing Up

### ISSUE THREAD

**Issue by brentlintner** [bithound/feedback#64]
It seems only TODO/HACK comments show up for JavaScript in a TypeScript project I am working on, where there are a number of HACK and TODOs throughout the codebase.

![selection_041](https://cloud.githubusercontent.com/assets/93340/7818113/9286aa46-03a7-11e5-92ea-a21e684c893c.png)

**Comment by CSilivestru** [comment]
Thanks @brentlintner!

We're investigating this internally and will update this issue with progress.

**Comment by Connoropolous** [comment]
Hey @brentlintner 

This was a missing component of our TypeScript feature that we've now added. The comments will get picked up in any new commits, or, if you'd like to see them on repos as they currently are, email us with the repos, or just comment here if they're open source!

**Comment by brentlintner** [comment]
Cool. Thanks @Connoropolous!
