### ISSUE TITLE
Automatic Multi Branch Analyzing?

### ISSUE THREAD

**Issue by brentlintner** [bithound/feedback#65]
It appears that non-master branches are automatically updated and re-analyzed?

As a user, I wonder if having the ability to turn this on/off in settings is ideal, as, I and many people I work with may rebase, amend or add onto branches and push those multiples times (in less than a minute at times).

**Comment by CSilivestru** [comment]
Could you please explain what made you think this is the behaviour for non-master branches? Currently, bitHound does not automatically update non-master branches. The only time when a re-analysis of a branch would occur would be if a user goes to that branch's dashboard page and bitHound detects some sort of delta, whether that be a straight line ancestral delta or a mismatched ancestry delta (in the case of a rebase).

If you were to visit the dashboard often while rebasing and pushing commits all the time then each new visit would trigger a re-analysis of the delta commits, provided there isn't a current analysis running for that repo.

Hope that all makes sense.... :-).

**Comment by brentlintner** [comment]
Oh snap. Apparently, I've mistaken ondemand *magic* for *automation* ;-)

Would just being on the page, vs (re)loading it, trigger an update? If that is the case, then I am even more so mistaken.

**Comment by CSilivestru** [comment]
Just ti clarify, simply staying on the page would not trigger new analysis BUT if someone else hit the page while you stayed on it, you would receive the updates as well.

Glad it was clear!
