### ISSUE TITLE
Wrong links in dashboard

### ISSUE THREAD

**Issue by jorool** [bithound/feedback#66]
The links in my dashboard are like
```
https://<user>/<repo>//dependencies/npm"
```
instead of 
```
https://www.bithound.io/bitbucket/<user>/<repo>/dependencies/npm
```

**Comment by CSilivestru** [comment]
Hi @jorool,

Github omits html tokens so I'm guessing you have text between \< and \> that isn't showing up. You can escape them with '/'.

**Comment by carlosperez** [comment]
HI @jorool – sorry about that. Can you let us know where on the page this link is?

**Comment by jorool** [comment]
Nevermind, man!
Sure! Is main menu of dashboar: "Dashboar, Dependencies, TechDebt...."
I think I got it. The problem was after analyze a project with no javascript!
With a project that has javascript, no probs.

**Comment by carlosperez** [comment]
Hi @jorool – good find! We'll keep this issue open to track it internally.

**Comment by jorool** [comment]
Cool.

**Comment by CSilivestru** [comment]
Hey @jorool,

We rolled out a fix for this -- thanks for bringing it up!
