### ISSUE TITLE
[TypeScript] 1.5 Is Out - Previous TSLint Thinks Decorator Syntax Is "Lint"

### ISSUE THREAD

**Issue by brentlintner** [bithound/feedback#67]
Currently 1.5 is in Beta, and (like the beta release of TSLint) it supports some nifty features, such as Decorators, which get linted incorrectly since the previous TSLint release does not recognize it.

If you can update it to use the new version when possible and convenient, that would be sweet. :-)

FWIW: It seems quite stable for us, but, I would understand the need to wait until it is out of beta to upgrade.

Thanks!

**Comment by Connoropolous** [comment]
Thanks Brent, we'll look into the update, and report back here!

**Comment by gtanner** [comment]
hey @brentlintner,

we had updated tslint to 2.4.2 a little bit ago so this should have fixed your issue.  I am going to close this. Feel free to open a new issue if you have any other typescript issues
