### ISSUE TITLE
Bithound(ing) what branch?

### ISSUE THREAD

**Issue by mathiasrw** [bithound/feedback#68]
Love it - that why I have only pitty small tiny details to grumple about...

1) Its pretty hard to see what branch I am in, in the dashboard. The only "clue" is a label named "master" at the top right of the main graph. Well - turns out its actually a button - indicating that you can to to the master master branch. Its not clear that this is not the actual branch, but a branch you can change to. 

2) Having blacklisted files its natural to click "see all blacklisted files" - but there I cant find the reason they are blacklisted - only if I click back to the dashboard and find the "learn more" (thats not always visible). WOud help out if each blacked listed file had the reason it was blacklisted on /files#blacklist

**Comment by mathiasrw** [comment]
Hmm. I see now that its at the top right.... 

Its a bit hidden up there...

**Comment by gtanner** [comment]
This is great feedback though!

UX is something we really try to focus on and we will look into what we can do to bring the branch out a bit more.

**Comment by mathiasrw** [comment]
:+1:

**Comment by gtanner** [comment]
Hey, during our recent redesign we moved the branch selector down a little bit (see: https://www.bithound.io/github/bithound/farm.bithound.io).

Hope that helped ;)

What are your thoughts on the new design?

**Comment by mathiasrw** [comment]
Looks great!
