### ISSUE TITLE
Linking to filter

### ISSUE THREAD

**Issue by mathiasrw** [bithound/feedback#69]
Would be good to be able to link to the filter im looking at. Forexamlpe:

https://www.bithound.io/github/agershun/alasql/blob/92ae293b40419e3bab0fe18893fc4873e0b72ade/src/17alasql.js

I copied the link when I was looking at only the lints - so would be nice if it included #lint so the filter was also transmitted :)

**Comment by carlosperez** [comment]
Hi @mathiasrw - good idea! We've just pushed out a small change that allows for this. Check it out: https://www.bithound.io/github/agershun/alasql/blob/92ae293b40419e3bab0fe18893fc4873e0b72ade/src/17alasql.js#filter-lint

**Comment by mathiasrw** [comment]
Nice job !
