### ISSUE TITLE
"Something went wrong" while analizing pygy/j2c (but the results look fine).

### ISSUE THREAD

**Issue by pygy** [bithound/feedback#70]
https://www.bithound.io/github/pygy/j2c/v0.8pre says that *"Something went wrong while analyzing this repository."*

I actually `rebased` and `push`ed `-f` that branch after a first analysis.

It took a lot of time for bithound to process the repo, but things are now looking fine.

Edit: Also, while it was apparently stuck, I pushed another branch pointing to the same commit to give it another chance to process it.

**Comment by pygy** [comment]
I renamed that branch to `next` in the mean time, and notice is gone.

I don't know if it is related, but I can't display the report for these files:

- https://www.bithound.io/github/pygy/j2c/blob/47a6ca3aa171bab3c680d554823649455fd62398/test/test.js
- https://www.bithound.io/github/pygy/j2c/blob/47a6ca3aa171bab3c680d554823649455fd62398/scripts/build.js

**Comment by CSilivestru** [comment]
Hello @pygy,

So sorry about this! Your original branch name should have been ok for processing as well as the rebase scenario you described. I just wanted to let you know that I'm currently looking into this and will update you here as soon as I have anything.

Thanks for your patience!

**Comment by CSilivestru** [comment]
Hi @pygy,

I've identified the issue and we just deployed a fix. I hit the url myself and everything is up and running. Thanks again for reporting this!

**Comment by pygy** [comment]
Great, thanks a lot. You're young and bugs happen :-).

Note that now (a file on the `next` branch), [this page](https://www.bithound.io/github/pygy/j2c/blob/47a6ca3aa171bab3c680d554823649455fd62398/test/test.js) shows a link to a "bigger fish to fry". 

The stats correspond to the file of the `master` branch, but clicking the link goes to the same file on `next`.

The `master` stats are worse BTW, but I'm not sure it is the intended behavior.

**Comment by CSilivestru** [comment]
Awesome find!

I've also identified this problem and we should have a fix out for it soon :-). I'll keep you posted.

**Comment by CSilivestru** [comment]
Hi @pygy,

We just deployed the fix and you should be all good now.

**Comment by pygy** [comment]
Great, thanks :-)
