### ISSUE TITLE
Empty lines

### ISSUE THREAD

**Issue by mathiasrw** [bithound/feedback#72]
Would be really nice if you counted the lines for "the file is too long" or size for "This file is too big" after removing comments from the code.

**Comment by dansilivestru** [comment]
Hi @mathiasrw, thanks for your feedback.

We have received this request before and we are looking at reducing the "impact" of comment lines on the overall length of the file. There is however an inherent ongoing cost to comments. It's not uncommon for them to become out of date and in some cases mislead the developer as a result.

BTW, came across this the other day and I thought it explained our thoughts rather well :-)
https://twitter.com/wraithgar/status/601497059577987073

I'll keep this issue open until we implement the file length changes and to keep you posted on our progress.

**Comment by mathiasrw** [comment]
:+1:

**Comment by mathiasrw** [comment]
Anything new?

**Comment by carlosperez** [comment]
Hi @mathiasrw – sorry letting this one linger to long. We haven't had a chance to take a close look at how we handle empty lines in our file length analysis. We are going to track this issue internally. Keep a an eye out on our newsletter, [changelog](https://www.bithound.io/changelog) and [blog](http://blog.bithound.io) for our feature updates.

**Comment by mathiasrw** [comment]
Sounds good 

For when you get the time to look at it: feel free to get inspired...

```
var linecount = fileContent
						.replace(/\/\*[\s\S]*?\*\//gm, '')	// remove /* ... */ comments
						.replace(/^\s*\/\/.*$/gm, '')		// remove //... comments
						.replace(/^\s*\r?\n/gm, '' )		// remove blank lines (not interesting for lincount of code)
						.split("\n").length
```

Im sure the technical side is not

**Comment by gtanner** [comment]
Hey @mathiasrw,  Just thought I would point you at http://blog.bithound.io/new-configuration-options/.

You can now configure our line count critic via your `.bithoundrc`.

**Comment by mathiasrw** [comment]
woohooo ! - thanks for that :)
