### ISSUE TITLE
Outdated Dependencies: Versions Are Cut Off?

### ISSUE THREAD

**Issue by brentlintner** [bithound/feedback#73]
![selection_046](https://cloud.githubusercontent.com/assets/93340/8015424/48d24de0-0ba6-11e5-865a-1b4b601c2ced.png)

The versions seem to be missing their last digits, and some perhaps more than the last. (ex: 1.0.0 is rendered as 1)

**Comment by carlosperez** [comment]
Thanks for pointing it out @brentlintner ! We'll take a look!

**Comment by carlosperez** [comment]
Hi @brentlintner – This *should* be fixed. Can you let me know if you are still seeing this issue?

**Comment by brentlintner** [comment]
@carlosperez looks good to me, now. :-)
