### ISSUE TITLE
Analysis won't complete

### ISSUE THREAD

**Issue by AlicanC** [bithound/feedback#74]
I have a fresh TypeScript project here:
https://github.com/movielala/LayeredConfigurator

Sadly, analysis of the repo won't complete:
https://www.bithound.io/github/movielala/LayeredConfigurator

Any help is appreciated.

**Comment by gtanner** [comment]
Hey @AlicanC, our back end services picked this repo up as having problems and we are investigating.

We will keep you posted but first look at it seems to be an issue with our TS linting configuration.

**Comment by AlicanC** [comment]
I am also not able to lint it. I traced my linting issue and ended up here:

https://github.com/palantir/tslint/issues/399

**Comment by gtanner** [comment]
thanks @AlicanC, will look into that issue as well.

I know updating tslint is on our list of things to do to fix this issue

**Comment by AlicanC** [comment]
It works now, thanks.

**Comment by gtanner** [comment]
Your welcome!

We pushed a fix for this yesterday and scheduled the reanalysis
