### ISSUE TITLE
Stop analysis?

### ISSUE THREAD

**Issue by okize** [bithound/feedback#75]
How to I stop analysis of a repository? ie. How do I move a repo from "analyzed projects" to "unanalyzed projects"?

Thank you!

**Comment by CSilivestru** [comment]
Hi @okize,

Please send me an email with the repo(s) you's like to stop analysis on. We don't currently have this functionality in the bitHound UI but we're working on it!

You can reach me at chris@bithound.io.
Thanks!

**Comment by okize** [comment]
Great, thanks @CSilivestru!

**Comment by okize** [comment]
hi Chris, could you stop the following repos?

okize/selector-detector-bookmarklet
okize/flubr
okize/desertislandsuicide.com

thanks!
Morgan

On Sun, Jun 14, 2015 at 12:02 PM, Chris Silivestru <notifications@github.com

**Comment by tonious** [comment]
Hi @okize,

I've removed these repos from our system entirely.  Let me know if there's anything else I can do.

Thanks!

  -- T.

**Comment by okize** [comment]
@tonious That's great, thank you!
