### ISSUE TITLE
_ is not defined

### ISSUE THREAD

**Issue by nevi-me** [bithound/feedback#76]
JSLint suffers from the problem of undefined variables, such as `$`, `_`, `google`, etc. I don't want to redefine vars from libraries just so I can get a better score. 
Any solutions? Otherwise Bithound is not reporting my score correctly

**Comment by gtanner** [comment]
You can customize the linting rules.  We have a blog post on that here (https://www.bithound.io/blog/post/customizing-jshint-on-bithound).

In your `.jshintrc` file you can specify known globals.

**Comment by nevi-me** [comment]
Thanks, will do that
