### ISSUE TITLE
False outdated dependency.

### ISSUE THREAD

**Issue by AlicanC** [bithound/feedback#77]
Here is my dependency report:
https://www.bithound.io/github/movielala/LayeredConfigurator/master/dependencies/npm

Gulp is flagged outdated because I use version 4.0 instead of the stable 3.9.0. I think one of these should happen instead:

- Assume I know what I am doing and don't put any flags on it.
- Assume I don't know what I am doing and put an "experimental" flag on it.

**Comment by CSilivestru** [comment]
Hi @AlicanC,

We've recently put out some improvements to how we handle dependency versions when it comes to the latest version versus the last stable version. It's now considered a 'custom' version and we no longer put badges on it. Thanks!

**Comment by AlicanC** [comment]
Cool, thanks.
