### ISSUE TITLE
Detect deprecated dependencies.

### ISSUE THREAD

**Issue by AlicanC** [bithound/feedback#78]
Here is my dependency report:
https://www.bithound.io/github/movielala/LayeredConfigurator/master/dependencies/npm

I use `gulp-rimraf` which is actually deprecated but no warnings are given for this.

`npm view gulp-rimraf`:
```javascript
{ ...stuff...,
  deprecated: 'Use npmjs.org/del instead, see https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md',
  ...stuff... }
```

**Comment by carlosperez** [comment]
Hi @AlicanC – thanks for the feedback on dependencies. You've given us some good things to think about as we look to improve our Dependencies support!

**Comment by gtanner** [comment]
Hey @AlicanC, you should totally check out https://www.bithound.io/github/movielala/LayeredConfigurator/master now :)

Let us know what you think.

**Comment by AlicanC** [comment]
Great implementation, thanks.

**Comment by AlicanC** [comment]
I don't think this reduces my score. Shouldn't it?

**Comment by gtanner** [comment]
Currently we don't use any of the dependencies data in the score, it is something on our radar for sure as we really feel that outdated, insecure, unused and deprecated dependencies are something that **should** be cleaned up.

**Comment by AlicanC** [comment]
That's great to hear.
