### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by mathiasrw** [bithound/feedback#79]
When I want to see what bower dependencies are outdated the browser gows to https://www.bithound.io/github/agershun/alasql/feature/code-quality/dependencies/bower
But the page states that

> Oops! Page not found!

> THE PAGE YOU REQUESTED WAS NOT FOUND. 
CHECK THE URL.

**Comment by CSilivestru** [comment]
Hi @mathiasrw,

Thanks for reporting this!
We url encode branch names with a '/' in them and it looks like we just missed a link on the dashboard page. I'll be fixing that up and I will update you here when it's been resolved.

As a temporary work around, you can replace the url with this and bitHound with route you properly:
'https://www.bithound.io/github/agershun/alasql/feature%2Fcode-quality/dependencies/bower'.

Sorry for the inconvenience!

**Comment by gtanner** [comment]
Hey @mathiasrw,

we pushed a fix to our dependencies view to fix up that broken link.
It will now be the proper encoded version.

Thanks for finding this for us!

**Comment by mathiasrw** [comment]
:+1:
