### ISSUE TITLE
Confusing graphic when files improve in a commit

### ISSUE THREAD

**Issue by sympmarc** [bithound/feedback#80]
I'd call this one a "graphics bug". I was working one of my files over the weekend, and each time I committed a new version, I thought bitHound was telling me I made the file *worse*, not better, as was actually the case.

If you look at the screen snippet, the 18.64 number has a down arrow. I took this to mean that I made the file 18.64 points *worse*. I was pretty confused until I finally caught the fact that the score (96 here) was actually going *up*.

![image](https://cloud.githubusercontent.com/assets/1295627/8281370/54cba008-18b5-11e5-8a36-8d4925479208.png)

You can see this in the followoing commits:
https://www.bithound.io/github/sympmarc/SPServices/commit/5d25732ae0f53ff6e9d84b9fc8b2ec2fae8e98f4
https://www.bithound.io/github/sympmarc/SPServices/commit/c768cc6df89026c8c00ac7b4c55fc3476f586d28
https://www.bithound.io/github/sympmarc/SPServices/commit/172bc7c27a7b385584df389e315edfdabebc382d

**Comment by carlosperez** [comment]
Thanks for pointing this out @sympmarc. We just refactored the component that handles the score changes and it looks like we introduced a bug there. We'll get it sorted out and get back to you!

**Comment by sympmarc** [comment]
Looks like it's fixed!
https://www.bithound.io/github/sympmarc/SPServices/commit/5d25732ae0f53ff6e9d84b9fc8b2ec2fae8e98f4

M.

**Comment by carlosperez** [comment]
Yes! We pushed out the change earlier. Looks like you got to it before I could update the issue here on GitHub! :smile:
