### ISSUE TITLE
several repos stuck on "fetching latest commits"

### ISSUE THREAD

**Issue by sagiegurari** [bithound/feedback#81]
Here are some of my repos that are stuck for some reason:

https://www.bithound.io/github/sagiegurari/angular-web-notification
https://www.bithound.io/github/sagiegurari/event-emitter-enhancer
https://www.bithound.io/github/sagiegurari/node-spider-script

**Comment by dansilivestru** [comment]
Hi @sagiegurari. Our apologies. The team is looking into this right now and we'll get back to you shortly.

**Comment by sagiegurari** [comment]
thanks

**Comment by CSilivestru** [comment]
Hi @sagiegurari,

It looks like these repos were put into an odd state in our queueing process but they should all be resolved and up to date now. Thanks for reporting this!

**Comment by sagiegurari** [comment]
thanks. works good.
