### ISSUE TITLE
Is it a bug?

### ISSUE THREAD

**Issue by mathiasrw** [bithound/feedback#83]
I got this on a file

```
BUG PRONE FILE
A high bugfix to total commits ratio indicates file instability. Take extra care when making changes here.
```

I agree... but how do you find out if its a bugfixing commit?

**Comment by dansilivestru** [comment]
Hi @mathiasrw,

Glad to hear that you agree with our conclusions on this piece of insight :) We do have some secret sauce that marks a commit as having been the result of a bug fix, I'm really sorry that I can't give you any more details yet :(

**Comment by mathiasrw** [comment]
Looks like its working - sweet !
