### ISSUE TITLE
Large Badge for README.md

### ISSUE THREAD

**Issue by dcrockwell** [bithound/feedback#84]
It would be nice if you could give a markdown snippet to display the full-size score in our README.md files:

![screen shot 2015-07-02 at 10 41 45 am](https://cloud.githubusercontent.com/assets/53482/8482460/fc7071f0-20a6-11e5-986f-43c339f39eb9.png)

**Comment by carlosperez** [comment]
Hi @dcrockwell - agreed! Improvements to our score badge is something we want to take a look at. I'll keep this issue open to track progress when we are able to address it.

**Comment by carlosperez** [comment]
Hi @dcrockwell – while we haven't created a large bitHound badge as you mention here (as we've changed what constitutes a project's overall score), we have started adding other badges for dependencies that you can [check out](http://blog.bithound.io/dependency-badges-are-here-for-your-projects-readme-file/). I'm going to close this issue for now and track it internally.
