### ISSUE TITLE
be able to provide the dependencies path in .bithoundrc

### ISSUE THREAD

**Issue by gion** [bithound/feedback#85]
I have a repo that has both npm and bower dependencies, but they aren't in the root folder. They are in the 3rd level folder and bithound tells me that there are no dependencies. 
A solution might be to have bithound scan the whole folder recursively for a *package.json* file, or **better**, maybe there should be some config options in the *.bithoundrc* to tell it where to look for certain dependencies

**Comment by carlosperez** [comment]
Hi @gion – thank you for the suggestions. We've known this to be an issue with our dependencies analysis, but this gives us some ideas on how we can address it. I'll open up an issue internally to keep this on our radar.

**Comment by gion** [comment]
Well, maybe my comment wasn't clear enough, but I did point out 2 possible solutions.  
Again, my suggestion would be to have this option configurable, and since you guys do have a file that stores some config data (I'm talking about the *.bithoundrc* file), maybe it would be OK to be able to set a dependency path in there.

**Comment by xinthink** [comment]
Facing the same problem.
I have a repo structured like this:

```
root
    |-- src
    |     |-- package.json
    |-- example
    |     |-- package.json
```

bitHound keep issuing the `ESLINT OUTDATED` warning.

It'll be great to be able to config through the `.bithoundrc` file to specify that `src/package.json` should be respected and `example/package.json` should be ignored.

**Comment by carlosperez** [comment]
Hi @gion and @xinthink – we've added the ability to specify the location of your `package.json` in your `.bithoundrc` file. Check out the blog post for more info: http://blog.bithound.io/support-for-a-custom-location-for-your-package-json-file/

**Comment by xinthink** [comment]
Its' awesome, thanks!
