### ISSUE TITLE
ES7 features supported?

### ISSUE THREAD

**Issue by wolframkriesing** [bithound/feedback#86]
I am using ES7 static properties, but this reports a lint error.
Is this at the horizont, or not in scope yet?
https://www.bithound.io/github/wolframkriesing/es6-react-workshop/blob/d8b7f521d7bc9448a50493f6b39ac0d74d4bc270/src/components/katagroups.js#8-lint

**Comment by wolframkriesing** [comment]
Can I configure it to use the .eslintrc? (which in this case here would mean to use the babel-eslint parser too :))

**Comment by dansilivestru** [comment]
I'm going to close this since we now offer support for this through our recent implementation of ESLint. You can now run custom rules on bitHound to have your project analyzed for ES7.
