### ISSUE TITLE
Locked in "there is no js" mode

### ISSUE THREAD

**Issue by Offirmo** [bithound/feedback#88]
I've tried bithound on a fresh new repo https://github.com/Offirmo/client-001-dependencies-check

Ok, I've been too hasty and asked bithound to analyse it while there were no .js files, only a package.json. (I was looking primarily after the dependency analysis)

BitHound rightfully complained "THERE'S NO JAVASCRIPT!"

Now **I added some js**. However, BitHound no longer wants to analyse my repo :
* in the dashboard, the repo is hidden under "1 of Offirmo's repositories cannot be analyzed."
* even if I try to manually enter the github url, BitHound still refuses to analyse and redirects me immediately to "THERE'S NO JAVASCRIPT!"

I couldn't find any "refresh" or "rescan" button.

Now I'm stuck. (And considering giving up evaluating BitHound)

**Comment by gtanner** [comment]
Hey,

We are just going to kick that off for you :)

Will will log fix that "rescan" issue shortly.

Thanks

**Comment by Offirmo** [comment]
That's great ! Hope my client 001 will enjoy the report :)

**Comment by gtanner** [comment]
Ran :) 
https://www.bithound.io/github/Offirmo/client-001-dependencies-check/master

**Comment by Offirmo** [comment]
I'm considering this issue closed. Close it at your discretion. Thanks for the fast answer.

**Comment by gtanner** [comment]
No problem,

we are keeping our eye on this repo today just to make sure things work smooth for you.

Happy Coding.
