### ISSUE TITLE
Loosing the security warnings on dependencies

### ISSUE THREAD

**Issue by Offirmo** [bithound/feedback#89]
I can't find the security warnings anymore in "Dependency Alerts" for https://www.bithound.io/github/Offirmo/client-001-dependencies-check/master

Steps to reproduce :

push a new commit

![bithound in progress](https://cloud.githubusercontent.com/assets/603503/8805335/fdabce78-2fd0-11e5-9c68-2612efa6b535.png)

and the security warnings show up again !

![bithound security](https://cloud.githubusercontent.com/assets/603503/8805349/13661b1a-2fd1-11e5-8b6a-877782838313.png)

However, as soon as I hit F5 or navigate to another page, security warnings are lost and I can't find them anymore in the dashboard

![kng](https://cloud.githubusercontent.com/assets/603503/8805355/1e8c2110-2fd1-11e5-8913-2f6769e39957.png)

What's happening ? Security analysis is a very interesting feature.

**Comment by gtanner** [comment]
Looking into it.

Will get back to you shortly.

**Comment by gtanner** [comment]
We found an edge case in the live updates to our security analysis that you managed to hit :cry: 

A hotfix is being created by @Connoropolous as we speak.

**Comment by gtanner** [comment]
So the hotfix ended up getting packaged into a larger deploy happening this evening.

Sorry for the delay.

**Comment by Offirmo** [comment]
Ok, issue closed from my side.

Am I unlucky with your tool ? Do you have end-to-end tests ?

**Comment by Connoropolous** [comment]
Hi Offirmo

There are some things that fall under a category of extreme difficulty to test, that will only get ironed out through use. In that sense, you had an unlucky moment with bitHound, yes. I do hope that now that your security vulnerabilities are being reported once again, that you'll get good use out of it!
