### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by bahmutov** [bithound/feedback#9]
Hi guys,
First, good job, love the UI and features. Definitely strong contender! Especially love the forecast on fixing issues plus duplicate code detection.

I have written a blog post a while ago on features I would like to see in a service similar to yours. Feel free to take these as suggestions http://bahmutov.calepin.co/code-quality-as-a-service.html

**Comment by gtanner** [comment]
Just closing this as it isn't really an issue to "fix" but rather a list of neat things to add to the pipeline in the future.
