### ISSUE TITLE
Long file warning should be overridable

### ISSUE THREAD

**Issue by TimBeyer** [bithound/feedback#90]
I realize it's a bit silly, but after finding out about bithound I decided I need to get a 100 rating for my repository. I've managed to address all issues, but `Long File` is simply not solvable because it's a large config file that isn't easily split (https://github.com/TimBeyer/html-to-vdom/blob/master/lib/get-property-info/htmldom/property-config.js).

Could there be a way to ignore warnings for cases like this so that people like me can get their 100?

**Comment by dansilivestru** [comment]
Hi @TimBeyer 

Very interesting point... I'm not sure if you're aware, but we already differentiate between "test/spec" files and "project" files. For test files, we don't penalize you very much (or at all in some cases) for having a long file. The reasoning being that most tests should be atomic and the file length does not often impact maintainability or quality in a negative way.

I wonder if we should consider a different scoring criteria for config files, build files, etc.

I'm going to keep this issue open for now as we discuss it internally and use it to keep you updated.

In the mean time, seeing that this is a config file, you can just ignore the file by telling bitHound not to analyze it using a .bithoundrc. The how-to is here: http://blog.bithound.io/ignoring-files-and-folders-in-bithound/

**Comment by andersevenrud** [comment]
:+1:

I have mentioned this to you before @dansilivestru, but does bithound take comments into consideration?

I have quite a few files that are *heavy* on documentation for methods etc. And if the file contains a copy of the LICENSE that adds a few dozen lines to the file.

**Comment by carlosperez** [comment]
Hi @TimBeyer and @andersevenrud Handling comments and config files to determine the file length warning is something we are investigating, but don't have a solid timeline on. We're going to track this issue internally going forward. Keep a an eye out on our newsletter, [changelog](https://www.bithound.io/changelog) and [blog](http://blog.bithound.io) for future feature updates.

**Comment by gtanner** [comment]
Hey @TimBeyer and @andersevenrud, just wanted to let you know we landed a feature for you http://blog.bithound.io/new-configuration-options/.

Let us know what you think!

**Comment by andersevenrud** [comment]
@gtanner Awesome! Going to apply this at once ! :)

**Comment by andersevenrud** [comment]
@gtanner A small note about the article:

```

"critics": {
    "wc": { limit: 5000 }
}

```

shouldn't it be like this (to make it valid):

```

"critics": {
    "wc": { "limit": 5000 } // <- quotes
}

```

**Comment by gtanner** [comment]
Well crap ;)

Thanks for that. Fixing the post now

**Comment by andersevenrud** [comment]
@gtanner Same thing applies to the "engine" parameter as well :)

**Comment by gtanner** [comment]
yeah, got them both, should be fine now

**Comment by andersevenrud** [comment]
:+1:

**Comment by andersevenrud** [comment]
@gtanner I applied the setting to my bithoundrc, but it still says *long file* even though I set it to 2000.

It finished scanning/processing without any errors. Is it cached and just me being impatient, or do I have to write/touch the files to make it trigger ?

**Comment by gtanner** [comment]
which repo? I can take a look.

**Comment by andersevenrud** [comment]
https://www.bithound.io/github/andersevenrud/OS.js-v2/master

**Comment by andersevenrud** [comment]
It seems to have worked for some files though. Example file that was not updated:

https://www.bithound.io/github/andersevenrud/OS.js-v2/blob/d188aee6d8fc1d18f784c9492ce5215806bf169c/src/client/javascript/application.js

> 402 lines long

**Comment by gtanner** [comment]
I see.

Think of the limit as the "biggest file I would ever allow".  In your case a file that is 2000 lines.

We allow a 10% grace window (up to 200 lines in your case) where we don't flag the file as long.

make sense?

So if https://www.bithound.io/github/andersevenrud/OS.js-v2/blob/d188aee6d8fc1d18f784c9492ce5215806bf169c/src/client/javascript/window.js is fine, you should set your limit to 20000.

**Comment by gtanner** [comment]
and I just checked out what OS.js does ... that is sooo cool!

**Comment by andersevenrud** [comment]
> make sense?

Yeah, I got that from the article :)

> So if https://www.bithound.io/github/andersevenrud/OS.js-v2/blob/d188aee6d8fc1d18f784c9492ce5215806bf169c/src/client/javascript/window.js is fine, you should set your limit to 20000.

Ehrm. That file is ~1800 lines long and I set the limit to 2000 -- I actually based my number based on this exact file. I feel that a little under 2000 is pretty much perfect in case of my setup.

In https://github.com/bithound/feedback/issues/90#issuecomment-161734979 I noted a file that is <300 lines that still says *long file*

**Comment by andersevenrud** [comment]
> and I just checked out what OS.js does ... that is sooo cool!

Yeah, it is kinda cool, huh ? :) At the moment it is a bit lacking in actual content, but that will all change next year. Some really cool features and collaboration stuff coming. So make sure to check back in now and then ;)

**Comment by gtanner** [comment]
I think I see where the wording is breaking down.

Setting a limit of 2000 means a file with 2000 lines scores 0 for length.
As well a file that is under 200 lines scores 100 for length.
A file with 201 lines and up are all long files, where the score trends to zero the bigger the file gets.

**Comment by andersevenrud** [comment]
@gtanner Ah. I think my brain got a bit confused and associated this setting with the actual `wc` command (Like when you do `wc -l`. It makes sense now)... combined with my lazy reading and excitement. Hehe. Now I get it and it works fine :)
