### ISSUE TITLE
Public repo issue

### ISSUE THREAD

**Issue by JosefJezek** [bithound/feedback#91]
I can not add this repo https://github.com/StartPolymer/polymer-starter-kit-plus

`Your organization is currently on a plan that doesn't allow you to analyze private repositories. To begin analysis on StartPolymer/polymer-starter-kit-plus you must upgrade the organizations plan.`

**Comment by carlosperez** [comment]
Hi @JosefJezek – we're looking into this and we will update you shortly. Thank you for bringing this to our attention.

**Comment by Connoropolous** [comment]
Hi @JosefJezek 

We've got that repository being analyzed for you, and the issue that you raised resolved! Thanks for letting us know, and keep us in the loop of any other issues if you encounter them with bitHound.
https://www.bithound.io/github/StartPolymer/polymer-starter-kit-plus
