### ISSUE TITLE
Some .jshintignore files/folders are not ignored

### ISSUE THREAD

**Issue by Aur0r** [bithound/feedback#92]
Hi, I have configured my project to use .jshintignore this is the content in the file:

webpack.production.config.js
webpack.config.js
test/
dist/
build/

But somehow I am getting warnings for the files "webpack.production.config.js" and build/lib/ie8support/consolePolyfill.js.

**Comment by dansilivestru** [comment]
Thanks for reporting this. We do respect .jshintignore but for linting only.

Your best best to completely exclude files and folders is to use a .bithoundrc file. More details here: http://blog.bithound.io/ignoring-files-and-folders-in-bithound/

I'm going to close this issue for now, but please do open it again should you have any question or need more details.
