### ISSUE TITLE
Outdated NPM package check should use the "latest" dist tag

### ISSUE THREAD

**Issue by yyx990803** [bithound/feedback#94]
Currently the latest version used in the outdated check is the version with the newest timestamp - but often times a package may have alpha/beta releases while tagging the current stable version as "latest". The outdated check should use the "latest" NPM dist tag version instead.

**Comment by CSilivestru** [comment]
Hi @yyx990803,

Good point! That tag is present _most_ of the time but isn't something we can depend on. Regardless, at the very least, we could use it and fallback to using the latest timestamp release as a plan B. Thanks for the suggestion.

We're also moving all issues internally and I suggest you keep up with our newsletter, [changelog](https://www.bithound.io/changelog) and [blog](http://blog.bithound.io) for future feature updates. As a result I will be closing this issue but we'll continue working on this issue.

Thanks!
