### ISSUE TITLE
Support for CSS, HTML, Polymer

### ISSUE THREAD

**Issue by JosefJezek** [bithound/feedback#97]
Could you add support for CSS, HTML, Polymer?

- https://github.com/Polymer/hydrolysis

**Comment by carlosperez** [comment]
Hi @JosefJezek – we love Polymer around here, and it is one of (amongst others) types of analysis we are considering. We'll keep you posted on any updates!

**Comment by JosefJezek** [comment]
I need for https://github.com/StartPolymer/polymer-starter-kit-plus ;-)

**Comment by carlosperez** [comment]
Hi @JosefJezek – I'm going to close this and track the issue internally. It is not currently on our roadmap, but we are always looking what else we can support with our code analysis.
