### ISSUE TITLE
Dependency analysis seems to miss ES6 imports

### ISSUE THREAD

**Issue by rictic** [bithound/feedback#98]
Bithound believes that almost all of polyup's dependencies are unused: https://www.bithound.io/github/PolymerLabs/polyup/master/dependencies/npm

Perhaps this is because polyup is written in ES6? e.g. the import for espree is here: https://github.com/PolymerLabs/polyup/blob/master/lib/upgrade_js.js#L14

**Comment by gtanner** [comment]
You are correct that we are missing ES6 imports.  We are using [https://www.npmjs.com/package/detective](https://www.npmjs.com/package/detective) to find the required modules.  I am going to see if I can update that module to work with ES6 as well.

**Comment by gtanner** [comment]
Hey @rictic, we just landed a patch to support ES6 requires and reanalyzed your project: https://www.bithound.io/github/PolymerLabs/polyup/master/dependencies/npm.

**Comment by rictic** [comment]
Sweet, thanks!
