### ISSUE TITLE
Internal Server Error on "dependencies" page

### ISSUE THREAD

**Issue by andersevenrud** [bithound/feedback#99]
Ever since your UI update I am getting "Internal Server Error" on 
https://www.bithound.io/github/andersevenrud/OS.js-v2/master/dependencies/npm

I've been trying most of the day and it does not seem intermittent.

**Comment by dansilivestru** [comment]
Hi @andersevenrud thanks so much for letting us know. We've seen this as well and are actively working on it. This issue is showing on a small number of our analyzed projects.

We'll keep you posted here as to our progress.

Apologies for the inconvenience.

**Comment by CSilivestru** [comment]
Hi @andersevenrud,

Just deployed a fix for this issue. Sorry again for the inconvenience. It turns out we were mishandling a 404 from github for your node-fs-extra dependency and that was causing the crash.

You should be all good now -- please let us know if you have any other problems.

**Comment by andersevenrud** [comment]
I can confirm it is working now.

Thanks @CSilivestru @dansilivestru :+1:
